MODULE MPL_MYGATHERV_MOD

#include "tsmbkind.h"

USE MPL_MPIF
USE MPL_DATA_MODULE
USE MPL_MESSAGE_MOD

IMPLICIT NONE
PRIVATE
PUBLIC MPL_MYGATHERV

LOGICAL :: LLABORT=.TRUE.

CONTAINS

! ------------------------------------------------------------------
SUBROUTINE MPL_MYGATHERV(PSEND,KSEND,PRECV,KRECV,KDISPL,KROOT,KCOMM)

REAL_B, INTENT(IN)  :: PSEND(:)
REAL_B, INTENT(OUT) :: PRECV(:)
INTEGER_M, INTENT(IN) :: KSEND, KRECV(:), KDISPL(:)
INTEGER_M, INTENT(IN) :: KROOT, KCOMM
INTEGER_M :: ierr

CALL MPI_GATHERV(PSEND,KSEND,MPI_REAL8, &
               & PRECV,KRECV,KDISPL,MPI_REAL8,KROOT-1,KCOMM,ierr)

IF (ierr/=0) CALL MPL_MESSAGE(ierr,'MPL_MYGATHERV',LDABORT=LLABORT)

END SUBROUTINE MPL_MYGATHERV
! ------------------------------------------------------------------

END MODULE MPL_MYGATHERV_MOD
