MODULE MPL_BROADCAST_MOD

!**** MPL_BROADCAST Message broadcast

!     Purpose.
!     --------
!     Broadcasts a message from the process with rank root
!     to all processes in the group.
!     NOTE: Unlike MPI_BCAST, only the ROOT process sends the message

!**   Interface.
!     ----------
!        CALL MPL_BROADCAST

!        Input required arguments :
!        -------------------------
!           PBUF     -  buffer containing message
!                       (can be type REAL*4, REAL*8 or INTEGER)
!           KTAG     -  message tag
!           KROOT    -  number of root process

!        Input optional arguments :
!        -------------------------
!           KCOMM    -  Communicator number if different from MPI_COMM_WORLD 
!                       or from that established as the default 
!                       by an MPL communicator routine
!           CDSTRING -  Character string for ABORT messages
!                       used when KERROR is not provided

!        Output required arguments :
!        -------------------------
!           none

!        Output optional arguments :
!        -------------------------
!           KERROR   -  return error code.     If not supplied, 
!                       MPL_BROADCAST aborts when an error is detected.
!     Author.
!     -------
!        D.Dent, M.Hamrud     ECMWF

!     Modifications.
!     --------------
!        Original: 2000-09-01

!     ------------------------------------------------------------------

#include "tsmbkind.h"

USE MPL_DATA_MODULE
USE MPL_MESSAGE_MOD
USE MPL_SEND_MOD
USE MPL_RECV_MOD

IMPLICIT NONE
PRIVATE

#include "mpif.h"      

INTEGER_M :: ICOUNT,ICOMM,IERROR,IPROC
LOGICAL :: LLABORT=.TRUE.

INTERFACE MPL_BROADCAST
MODULE PROCEDURE MPL_BROADCAST_REAL4,MPL_BROADCAST_REAL8, &
     & MPL_BROADCAST_REAL42,MPL_BROADCAST_REAL82,         &
     & MPL_BROADCAST_INT,MPL_BROADCAST_INT2,MPL_BROADCAST_INT_SCALAR
END INTERFACE

PUBLIC MPL_BROADCAST

CONTAINS

SUBROUTINE MPL_BROADCAST_REAL4(PBUF,KTAG,KCOMM,KROOT,KERROR,CDSTRING)

! real_m,intent(in) :: PBUF(:)
REAL_M            :: PBUF(:)

INTEGER_M,INTENT(IN)          :: KROOT,KTAG
INTEGER_M,INTENT(IN),OPTIONAL :: KCOMM
INTEGER_M,INTENT(OUT),OPTIONAL :: KERROR

CHARACTER*(*),INTENT(IN),OPTIONAL :: CDSTRING

IF(PRESENT(KCOMM)) THEN
  ICOMM=KCOMM
ELSE
  ICOMM=MPL_COMM
ENDIF

ICOUNT = SIZE(PBUF)

IF(MPL_RANK == KROOT) THEN
  DO IPROC=1,MPL_NUMPROC
    IF(IPROC /= MPL_RANK) THEN
      CALL MPL_SEND(PBUF,KDEST=MPL_IDS(IPROC),KTAG=KTAG,KERROR=IERROR)
    ENDIF
  ENDDO
ELSE
  CALL MPL_RECV(PBUF,KSOURCE=KROOT,KTAG=KTAG,KERROR=IERROR)
ENDIF

IF(PRESENT(KERROR)) THEN
  KERROR=IERROR
ELSE
  IF(IERROR /= 0 ) CALL MPL_MESSAGE(IERROR,'MPL_BROADCAST',CDSTRING,LDABORT=LLABORT)
ENDIF

IF(MPL_OUTPUT > 1 )THEN
  WRITE(MPL_UNIT,'(A,5I8)') ' MPL_BROADCAST ',ICOUNT,KROOT,KTAG,ICOMM
ENDIF

END SUBROUTINE MPL_BROADCAST_REAL4

SUBROUTINE MPL_BROADCAST_REAL8(PBUF,KTAG,KCOMM,KROOT,KERROR,CDSTRING)

! real,intent(in) :: PBUF(:)
REAL_B            :: PBUF(:)

INTEGER_M,INTENT(IN)          :: KROOT,KTAG
INTEGER_M,INTENT(IN),OPTIONAL :: KCOMM
INTEGER_M,INTENT(OUT),OPTIONAL :: KERROR

CHARACTER*(*),INTENT(IN),OPTIONAL :: CDSTRING

IF(PRESENT(KCOMM)) THEN
  ICOMM=KCOMM
ELSE
  ICOMM=MPL_COMM
ENDIF

ICOUNT = SIZE(PBUF)

IF(MPL_RANK == KROOT) THEN
  DO IPROC=1,MPL_NUMPROC
    IF(IPROC /= MPL_RANK) THEN
      CALL MPL_SEND(PBUF,KDEST=MPL_IDS(IPROC),KTAG=KTAG,KERROR=IERROR)
    ENDIF
  ENDDO
ELSE
  CALL MPL_RECV(PBUF,KSOURCE=KROOT,KTAG=KTAG,KERROR=IERROR)
ENDIF



IF(PRESENT(KERROR)) THEN
  KERROR=IERROR
ELSE
  IF(IERROR /= 0 ) CALL MPL_MESSAGE(IERROR,'MPL_BROADCAST',CDSTRING,LDABORT=LLABORT)
ENDIF

IF(MPL_OUTPUT > 1 )THEN
  WRITE(MPL_UNIT,'(A,5I8)') ' MPL_BROADCAST ',ICOUNT,KROOT,KTAG,ICOMM
ENDIF

END SUBROUTINE MPL_BROADCAST_REAL8

SUBROUTINE MPL_BROADCAST_REAL42(PBUF,KTAG,KCOMM,KROOT,KERROR,CDSTRING)

! real_m,intent(in) :: PBUF(:,:)
REAL_M            :: PBUF(:,:)

INTEGER_M,INTENT(IN)          :: KROOT,KTAG
INTEGER_M,INTENT(IN),OPTIONAL :: KCOMM
INTEGER_M,INTENT(OUT),OPTIONAL :: KERROR

CHARACTER*(*),INTENT(IN),OPTIONAL :: CDSTRING

IF(PRESENT(KCOMM)) THEN
  ICOMM=KCOMM
ELSE
  ICOMM=MPL_COMM
ENDIF

ICOUNT = SIZE(PBUF)

IF(MPL_RANK == KROOT) THEN
  DO IPROC=1,MPL_NUMPROC
    IF(IPROC /= MPL_RANK) THEN
      CALL MPL_SEND(PBUF,KDEST=MPL_IDS(IPROC),KTAG=KTAG,KERROR=IERROR)
    ENDIF
  ENDDO
ELSE
  CALL MPL_RECV(PBUF,KSOURCE=KROOT,KTAG=KTAG,KERROR=IERROR)
ENDIF

IF(PRESENT(KERROR)) THEN
  KERROR=IERROR
ELSE
  IF(IERROR /= 0 ) CALL MPL_MESSAGE(IERROR,'MPL_BROADCAST',CDSTRING,LDABORT=LLABORT)
ENDIF

IF(MPL_OUTPUT > 1 )THEN
  WRITE(MPL_UNIT,'(A,5I8)') ' MPL_BROADCAST ',ICOUNT,KROOT,KTAG,ICOMM
ENDIF

END SUBROUTINE MPL_BROADCAST_REAL42

SUBROUTINE MPL_BROADCAST_REAL82(PBUF,KTAG,KCOMM,KROOT,KERROR,CDSTRING)

! real,intent(in) :: PBUF(:,:)
REAL_B            :: PBUF(:,:)

INTEGER_M,INTENT(IN)          :: KROOT,KTAG
INTEGER_M,INTENT(IN),OPTIONAL :: KCOMM
INTEGER_M,INTENT(OUT),OPTIONAL :: KERROR

CHARACTER*(*),INTENT(IN),OPTIONAL :: CDSTRING

IF(PRESENT(KCOMM)) THEN
  ICOMM=KCOMM
ELSE
  ICOMM=MPL_COMM
ENDIF

ICOUNT = SIZE(PBUF)

IF(MPL_RANK == KROOT) THEN
  DO IPROC=1,MPL_NUMPROC
    IF(IPROC /= MPL_RANK) THEN
      CALL MPL_SEND(PBUF,KDEST=MPL_IDS(IPROC),KTAG=KTAG,KERROR=IERROR)
    ENDIF
  ENDDO
ELSE
  CALL MPL_RECV(PBUF,KSOURCE=KROOT,KTAG=KTAG,KERROR=IERROR)
ENDIF



IF(PRESENT(KERROR)) THEN
  KERROR=IERROR
ELSE
  IF(IERROR /= 0 ) CALL MPL_MESSAGE(IERROR,'MPL_BROADCAST',CDSTRING,LDABORT=LLABORT)
ENDIF

IF(MPL_OUTPUT > 1 )THEN
  WRITE(MPL_UNIT,'(A,5I8)') ' MPL_BROADCAST ',ICOUNT,KROOT,KTAG,ICOMM
ENDIF

END SUBROUTINE MPL_BROADCAST_REAL82

SUBROUTINE MPL_BROADCAST_INT(KBUF,KTAG,KCOMM,KROOT,KERROR,CDSTRING)

! integer_m,intent(in) :: KBUF(:)
INTEGER_M           :: KBUF(:)

INTEGER_M,INTENT(IN)          :: KROOT,KTAG
INTEGER_M,INTENT(IN),OPTIONAL :: KCOMM
INTEGER_M,INTENT(OUT),OPTIONAL :: KERROR

CHARACTER*(*),INTENT(IN),OPTIONAL :: CDSTRING

IF(PRESENT(KCOMM)) THEN
  ICOMM=KCOMM
ELSE
  ICOMM=MPL_COMM
ENDIF

ICOUNT = SIZE(KBUF)

IF(MPL_RANK == KROOT) THEN
  DO IPROC=1,MPL_NUMPROC
    IF(IPROC /= MPL_RANK) THEN
      CALL MPL_SEND(KBUF,KDEST=MPL_IDS(IPROC),KTAG=KTAG,KERROR=IERROR)
    ENDIF
  ENDDO
ELSE
  CALL MPL_RECV(KBUF,KSOURCE=KROOT,KTAG=KTAG,KERROR=IERROR)
ENDIF


IF(PRESENT(KERROR)) THEN
  KERROR=IERROR
ELSE
  IF(IERROR /= 0 ) CALL MPL_MESSAGE(IERROR,'MPL_BROADCAST',CDSTRING,LDABORT=LLABORT)
ENDIF

IF(MPL_OUTPUT > 1 )THEN
  WRITE(MPL_UNIT,'(A,5I8)') ' MPL_BROADCAST ',ICOUNT,KROOT,KTAG,ICOMM
ENDIF

END SUBROUTINE MPL_BROADCAST_INT

SUBROUTINE MPL_BROADCAST_INT2(KBUF,KTAG,KCOMM,KROOT,KERROR,CDSTRING)

! integer_m,intent(in) :: KBUF(:,:)
INTEGER_M           :: KBUF(:,:)

INTEGER_M,INTENT(IN)          :: KROOT,KTAG
INTEGER_M,INTENT(IN),OPTIONAL :: KCOMM
INTEGER_M,INTENT(OUT),OPTIONAL :: KERROR

CHARACTER*(*),INTENT(IN),OPTIONAL :: CDSTRING

IF(PRESENT(KCOMM)) THEN
  ICOMM=KCOMM
ELSE
  ICOMM=MPL_COMM
ENDIF

ICOUNT = SIZE(KBUF)

IF(MPL_RANK == KROOT) THEN
  DO IPROC=1,MPL_NUMPROC
    IF(IPROC /= MPL_RANK) THEN
      CALL MPL_SEND(KBUF,KDEST=MPL_IDS(IPROC),KTAG=KTAG,KERROR=IERROR)
    ENDIF
  ENDDO
ELSE
  CALL MPL_RECV(KBUF,KSOURCE=KROOT,KTAG=KTAG,KERROR=IERROR)
ENDIF


IF(PRESENT(KERROR)) THEN
  KERROR=IERROR
ELSE
  IF(IERROR /= 0 ) CALL MPL_MESSAGE(IERROR,'MPL_BROADCAST',CDSTRING,LDABORT=LLABORT)
ENDIF

IF(MPL_OUTPUT > 1 )THEN
  WRITE(MPL_UNIT,'(A,5I8)') ' MPL_BROADCAST ',ICOUNT,KROOT,KTAG,ICOMM
ENDIF

END SUBROUTINE MPL_BROADCAST_INT2

SUBROUTINE MPL_BROADCAST_INT_SCALAR(KBUF,KTAG,KCOMM,KROOT,KERROR,CDSTRING)

INTEGER_M           :: KBUF

INTEGER_M,INTENT(IN)          :: KROOT,KTAG
INTEGER_M,INTENT(IN),OPTIONAL :: KCOMM
INTEGER_M,INTENT(OUT),OPTIONAL :: KERROR

CHARACTER*(*),INTENT(IN),OPTIONAL :: CDSTRING

IF(PRESENT(KCOMM)) THEN
  ICOMM=KCOMM
ELSE
  ICOMM=MPL_COMM
ENDIF

IF(MPL_RANK == KROOT) THEN
  DO IPROC=1,MPL_NUMPROC
    IF(IPROC /= MPL_RANK) THEN
      CALL MPL_SEND(KBUF,KDEST=MPL_IDS(IPROC),KTAG=KTAG,KERROR=IERROR)
    ENDIF
  ENDDO
ELSE
  CALL MPL_RECV(KBUF,KSOURCE=KROOT,KTAG=KTAG,KERROR=IERROR)
ENDIF


IF(PRESENT(KERROR)) THEN
  KERROR=IERROR
ELSE
  IF(IERROR /= 0 ) CALL MPL_MESSAGE(IERROR,'MPL_BROADCAST',CDSTRING,LDABORT=LLABORT)
ENDIF

IF(MPL_OUTPUT > 1 )THEN
  WRITE(MPL_UNIT,'(A,5I8)') ' MPL_BROADCAST ',ICOUNT,KROOT,KTAG,ICOMM
ENDIF

END SUBROUTINE MPL_BROADCAST_INT_SCALAR

END MODULE MPL_BROADCAST_MOD
