MODULE MPL_SCATTERV_MOD

#include "tsmbkind.h"

USE MPL_MPIF
USE MPL_DATA_MODULE
USE MPL_MESSAGE_MOD

IMPLICIT NONE
PRIVATE
PUBLIC MPL_SCATTERV

LOGICAL :: LLABORT=.TRUE.

CONTAINS

! ------------------------------------------------------------------
SUBROUTINE MPL_SCATTERV(PSEND,KSEND,KDISPL,PRECV,KRECV,KROOT,KCOMM)

REAL_B, INTENT(IN)  :: PSEND(:)
REAL_B, INTENT(OUT) :: PRECV(:)
INTEGER_M, INTENT(IN) :: KSEND(:), KDISPL(:), KRECV
INTEGER_M, INTENT(IN) :: KROOT, KCOMM
INTEGER_M :: ierr

CALL MPI_SCATTERV(PSEND,KSEND,KDISPL,MPI_REAL8, &
                & PRECV,KRECV,MPI_REAL8,KROOT-1,KCOMM,ierr)

IF (ierr/=0) CALL MPL_MESSAGE(ierr,'MPL_SCATTERV',LDABORT=LLABORT)

END SUBROUTINE MPL_SCATTERV
! ------------------------------------------------------------------

END MODULE MPL_SCATTERV_MOD
