! (C) Copyright 2005- ECMWF.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!


SUBROUTINE CMPL_ABORT(CDMESS)
USE MPL_MODULE
IMPLICIT NONE
CHARACTER(LEN=*) CDMESS
CALL MPL_ABORT(CDMESS)
END SUBROUTINE CMPL_ABORT

SUBROUTINE CMPI_ABORT(KRC)
USE MPL_MPIF, ONLY : MPI_COMM_WORLD
IMPLICIT NONE
INTEGER,INTENT(IN) :: KRC
INTEGER :: IRET
CALL MPI_ABORT(MPI_COMM_WORLD,KRC,IRET)
END SUBROUTINE CMPI_ABORT

SUBROUTINE CMPL_INIT(LDTRMSG,KERROR)
USE MPL_MODULE
IMPLICIT NONE
LOGICAL LDTRMSG
INTEGER KERROR
CALL MPL_INIT(KERROR=KERROR,LDINFO=.FALSE.)
END SUBROUTINE CMPL_INIT

FUNCTION CMPL_NPROC()
USE MPL_MODULE
IMPLICIT NONE
INTEGER CMPL_NPROC
CMPL_NPROC=MPL_NPROC()
END FUNCTION CMPL_NPROC

FUNCTION CMPL_MYRANK()
USE MPL_MODULE
IMPLICIT NONE
INTEGER CMPL_MYRANK
CMPL_MYRANK=MPL_MYRANK()
END FUNCTION CMPL_MYRANK

SUBROUTINE CMPL_BARRIER(KERROR)
USE MPL_MODULE
IMPLICIT NONE
INTEGER KERROR
CALL MPL_BARRIER(KERROR=KERROR)
END SUBROUTINE CMPL_BARRIER

SUBROUTINE CMPL_END(KERROR)
USE MPL_MODULE
IMPLICIT NONE
INTEGER KERROR
CALL MPL_END(KERROR=KERROR)
END SUBROUTINE CMPL_END

SUBROUTINE CMPL_GETARG(KARGNO, CDARG)
USE MPL_MODULE
IMPLICIT NONE
INTEGER KARGNO
CHARACTER(LEN=*) CDARG
CALL MPL_GETARG(KARGNO, CDARG)
END SUBROUTINE CMPL_GETARG

FUNCTION CMPL_IARGC()
USE MPL_MODULE
IMPLICIT NONE
INTEGER CMPL_IARGC
CMPL_IARGC = MPL_IARGC()
END FUNCTION CMPL_IARGC
