! (C) Copyright 2024- ECMWF.
! (C) Copyright 2024- Meteo-France.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

MODULE MPI_F08

INTEGER :: MPI_UNDEFINED, MPI_MAX_ERROR_STRING, MPI_ANY_TAG, MPI_ANY_SOURCE, &
 &         MPI_IDENT, MPI_CONGRUENT, MPI_SIMILAR, MPI_THREAD_SINGLE, MPI_THREAD_MULTIPLE, &
 &         MPI_MODE_RDONLY, MPI_MODE_WRONLY, MPI_MODE_CREATE, MPI_ERR_UNKNOWN

!! dummy type definitions
!!========================

TYPE MPI_COMM
  INTEGER :: MPI_VAL
END TYPE

TYPE MPI_DATATYPE
  INTEGER :: MPI_VAL
END TYPE

TYPE MPI_STATUS
  INTEGER :: MPI_TAG, MPI_SOURCE
END TYPE

TYPE MPI_REQUEST
  INTEGER :: MPI_VAL
END TYPE

TYPE MPI_FILE
  INTEGER :: MPI_VAL
END TYPE

TYPE MPI_OP
END TYPE

TYPE MPI_GROUP
END TYPE

TYPE MPI_INFO
END TYPE


!! dummy instances
!!=================

TYPE(MPI_DATATYPE) :: MPI_BYTE, MPI_LOGICAL, MPI_CHARACTER, MPI_INTEGER, MPI_INTEGER4, MPI_INTEGER8, MPI_REAL4, MPI_REAL8

TYPE(MPI_OP)       :: MPI_MAX, MPI_MIN, MPI_SUM, MPI_BXOR

TYPE(MPI_REQUEST)  :: MPI_REQUEST_NULL

TYPE(MPI_COMM)     :: MPI_COMM_WORLD, MPI_COMM_NULL

TYPE(MPI_INFO)     :: MPI_INFO_NULL

!! symbols defined in mpi_serial library, and picked up via a 'USE MPL_MPI' important statement
!!==============================================================================================

EXTERNAL :: MPI_COMM_SIZE, MPI_COMM_RANK, MPI_TYPE_SIZE, MPI_COMM_CREATE, MPI_COMM_GROUP, &
 &          MPI_INITIALIZED, MPI_FINALIZED, MPI_INIT, MPI_FINALIZE, MPI_BARRIER, &
 &          MPI_ABORT, MPI_COMM_FREE, MPI_COMM_SPLIT, MPI_COMM_COMPARE, MPI_GROUP_INCL, &
 &          MPI_FILE_OPEN, MPI_FILE_CLOSE, MPI_FILE_READ_SHARED, MPI_FILE_WRITE_SHARED, &
 &          MPI_FILE_WRITE_ORDERED, MPI_FILE_IWRITE_SHARED, MPI_FILE_READ_ORDERED,&
 &          MPI_FILE_IREAD_SHARED, MPI_FILE_READ_ORDERED_BEGIN, MPI_FILE_READ_ORDERED_END, &
 &          MPI_FILE_WRITE_ORDERED_BEGIN, MPI_FILE_WRITE_ORDERED_END, &
 &          MPI_BUFFER_ATTACH, MPI_BUFFER_DETACH, &
 &          MPI_ERROR_STRING, MPI_WAIT, MPI_WAITALL, MPI_WAITANY, MPI_TESTSOME, MPI_WAITSOME, &
 &          MPI_CART_CREATE, MPI_CART_COORDS, MPI_CART_SUB, MPI_CART_RANK, &
 &          MPI_PROBE, MPI_IPROBE, MPI_GET_COUNT, MPI_INIT_THREAD

CONTAINS

   ! Following are used in MPL with assumed rank and so they need an explicit interface
   SUBROUTINE MPI_ALLGATHERV(SEND_BUF, SEND_COUNT, SEND_TYPE, RECV_BUF, RECV_COUNTS, RECV_DISPLS, RECV_TYPE, COMM, IERROR)
     TYPE(*), INTENT(IN) :: SEND_BUF(..)
     INTEGER, INTENT(IN) :: SEND_COUNT
     TYPE(MPI_DATATYPE), INTENT(IN) :: SEND_TYPE
     TYPE(*), INTENT(INOUT) :: RECV_BUF(..)
     INTEGER, INTENT(IN) :: RECV_COUNTS(:)
     INTEGER, INTENT(IN) :: RECV_DISPLS(:)
     TYPE(MPI_DATATYPE), INTENT(IN) :: RECV_TYPE
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_ALLGATHERV

   SUBROUTINE MPI_IALLGATHERV(SEND_BUF, SEND_COUNT, SEND_TYPE, RECV_BUF, RECV_COUNTS, RECV_DISPLS, RECV_TYPE, COMM, REQUEST, IERROR)
     TYPE(*), INTENT(IN) :: SEND_BUF(..)
     INTEGER, INTENT(IN) :: SEND_COUNT
     TYPE(MPI_DATATYPE), INTENT(IN) :: SEND_TYPE
     TYPE(*), INTENT(INOUT) :: RECV_BUF(..)
     INTEGER, INTENT(IN) :: RECV_COUNTS(:)
     INTEGER, INTENT(IN) :: RECV_DISPLS(:)
     TYPE(MPI_DATATYPE), INTENT(IN) :: RECV_TYPE
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     TYPE(MPI_REQUEST), INTENT(OUT) :: REQUEST
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_IALLGATHERV

   SUBROUTINE MPI_ALLREDUCE(SEND_BUF, RECV_BUF, COUNT, DATATYPE, OP, COMM, IERROR)
     TYPE(*), INTENT(IN) :: SEND_BUF(..)
     TYPE(*), INTENT(INOUT) :: RECV_BUF(..)
     INTEGER, INTENT(IN) :: COUNT
     TYPE(MPI_DATATYPE), INTENT(IN) :: DATATYPE
     TYPE(MPI_OP), INTENT(IN) :: OP
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_ALLREDUCE

   SUBROUTINE MPI_ALLTOALLV(SEND_BUF, SEND_COUNTS, SEND_DISPLS, SEND_TYPE, RECV_BUF, RECV_COUNTS, RECV_DISPLS, RECV_TYPE, COMM, IERROR)
     TYPE(*), INTENT(IN) :: SEND_BUF(..)
     INTEGER, INTENT(IN) :: SEND_COUNTS(:)
     INTEGER, INTENT(IN) :: SEND_DISPLS(:)
     TYPE(MPI_DATATYPE), INTENT(IN) :: SEND_TYPE
     TYPE(*), INTENT(INOUT) :: RECV_BUF(..)
     INTEGER, INTENT(IN) :: RECV_COUNTS(:)
     INTEGER, INTENT(IN) :: RECV_DISPLS(:)
     TYPE(MPI_DATATYPE), INTENT(IN) :: RECV_TYPE
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_ALLTOALLV

   SUBROUTINE MPI_IALLTOALLV(SEND_BUF, SEND_COUNTS, SEND_DISPLS, SEND_TYPE, RECV_BUF, RECV_COUNTS, RECV_DISPLS, RECV_TYPE, COMM, REQUEST, IERROR)
     TYPE(*), INTENT(IN) :: SEND_BUF(..)
     INTEGER, INTENT(IN) :: SEND_COUNTS(:)
     INTEGER, INTENT(IN) :: SEND_DISPLS(:)
     TYPE(MPI_DATATYPE), INTENT(IN) :: SEND_TYPE
     TYPE(*), INTENT(INOUT) :: RECV_BUF(..)
     INTEGER, INTENT(IN) :: RECV_COUNTS(:)
     INTEGER, INTENT(IN) :: RECV_DISPLS(:)
     TYPE(MPI_DATATYPE), INTENT(IN) :: RECV_TYPE
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     TYPE(MPI_REQUEST), INTENT(OUT) :: REQUEST
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_IALLTOALLV

   SUBROUTINE MPI_BCAST(SEND_BUF, COUNT, DATATYPE, ROOT, COMM, IERROR)
     TYPE(*), INTENT(IN) :: SEND_BUF(..)
     INTEGER, INTENT(IN) :: COUNT
     TYPE(MPI_DATATYPE), INTENT(IN) :: DATATYPE
     INTEGER, INTENT(IN) :: ROOT
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_BCAST

   SUBROUTINE MPI_IBCAST(SEND_BUF, COUNT, DATATYPE, ROOT, COMM, REQUEST, IERROR)
     TYPE(*), INTENT(IN) :: SEND_BUF(..)
     INTEGER, INTENT(IN) :: COUNT
     TYPE(MPI_DATATYPE), INTENT(IN) :: DATATYPE
     INTEGER, INTENT(IN) :: ROOT
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     TYPE(MPI_REQUEST), INTENT(OUT) :: REQUEST
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_IBCAST

   SUBROUTINE MPI_GATHERV(SEND_BUF, SEND_COUNT, SEND_TYPE, RECV_BUF, RECV_COUNTS, RECV_DISPLS, RECV_TYPE, ROOT, COMM, IERROR)
     TYPE(*), INTENT(IN) :: SEND_BUF(..)
     INTEGER, INTENT(IN) :: SEND_COUNT
     TYPE(MPI_DATATYPE), INTENT(IN) :: SEND_TYPE
     TYPE(*), INTENT(INOUT) :: RECV_BUF(..)
     INTEGER, INTENT(IN) :: RECV_COUNTS(:)
     INTEGER, INTENT(IN) :: RECV_DISPLS(:)
     TYPE(MPI_DATATYPE), INTENT(IN) :: RECV_TYPE
     INTEGER, INTENT(IN) :: ROOT
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_GATHERV

   SUBROUTINE MPI_IGATHERV(SEND_BUF, SEND_COUNT, SEND_TYPE, RECV_BUF, RECV_COUNTS, RECV_DISPLS, RECV_TYPE, ROOT, COMM, REQUEST, IERROR)
     TYPE(*), INTENT(IN) :: SEND_BUF(..)
     INTEGER, INTENT(IN) :: SEND_COUNT
     TYPE(MPI_DATATYPE), INTENT(IN) :: SEND_TYPE
     TYPE(*), INTENT(INOUT) :: RECV_BUF(..)
     INTEGER, INTENT(IN) :: RECV_COUNTS(:)
     INTEGER, INTENT(IN) :: RECV_DISPLS(:)
     TYPE(MPI_DATATYPE), INTENT(IN) :: RECV_TYPE
     INTEGER, INTENT(IN) :: ROOT
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     TYPE(MPI_REQUEST), INTENT(OUT) :: REQUEST
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_IGATHERV

   SUBROUTINE MPI_RECV(BUF, COUNT, DATATYPE, SOURCE, TAG, COMM, STATUS, IERROR)
     TYPE(*), INTENT(INOUT) :: BUF(..)
     INTEGER, INTENT(IN) :: COUNT
     TYPE(MPI_DATATYPE), INTENT(IN) :: DATATYPE
     INTEGER, INTENT(IN) :: SOURCE
     INTEGER, INTENT(IN) :: TAG
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     TYPE(MPI_STATUS), INTENT(OUT) :: STATUS
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_RECV

   SUBROUTINE MPI_IRECV(BUF, COUNT, DATATYPE, SOURCE, TAG, COMM, REQUEST, IERROR)
     TYPE(*), INTENT(INOUT) :: BUF(..)
     INTEGER, INTENT(IN) :: COUNT
     TYPE(MPI_DATATYPE), INTENT(IN) :: DATATYPE
     INTEGER, INTENT(IN) :: SOURCE
     INTEGER, INTENT(IN) :: TAG
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     TYPE(MPI_REQUEST), INTENT(OUT) :: REQUEST
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_IRECV

   SUBROUTINE MPI_SCATTERV(SEND_BUF, SEND_COUNTS, SEND_DISPLS, SEND_TYPE, RECV_BUF, RECV_COUNT, RECV_TYPE, ROOT, COMM, IERROR)
     TYPE(*), INTENT(IN) :: SEND_BUF(..)
     INTEGER, INTENT(IN) :: SEND_COUNTS(:)
     INTEGER, INTENT(IN) :: SEND_DISPLS(:)
     TYPE(MPI_DATATYPE), INTENT(IN) :: SEND_TYPE
     TYPE(*), INTENT(INOUT) :: RECV_BUF(..)
     INTEGER, INTENT(IN) :: RECV_COUNT
     TYPE(MPI_DATATYPE), INTENT(IN) :: RECV_TYPE
     INTEGER, INTENT(IN) :: ROOT
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_SCATTERV

   SUBROUTINE MPI_ISCATTERV(SEND_BUF, SEND_COUNTS, SEND_DISPLS, SEND_TYPE, RECV_BUF, RECV_COUNT, RECV_TYPE, ROOT, COMM, REQUEST, IERROR)
     TYPE(*), INTENT(IN) :: SEND_BUF(..)
     INTEGER, INTENT(IN) :: SEND_COUNTS(:)
     INTEGER, INTENT(IN) :: SEND_DISPLS(:)
     TYPE(MPI_DATATYPE), INTENT(IN) :: SEND_TYPE
     TYPE(*), INTENT(INOUT) :: RECV_BUF(..)
     INTEGER, INTENT(IN) :: RECV_COUNT
     TYPE(MPI_DATATYPE), INTENT(IN) :: RECV_TYPE
     INTEGER, INTENT(IN) :: ROOT
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     TYPE(MPI_REQUEST), INTENT(OUT) :: REQUEST
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_ISCATTERV

   SUBROUTINE MPI_SEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, IERROR)
     TYPE(*), INTENT(IN) :: BUF(..)
     INTEGER, INTENT(IN) :: COUNT
     TYPE(MPI_DATATYPE), INTENT(IN) :: DATATYPE
     INTEGER, INTENT(IN) :: DEST
     INTEGER, INTENT(IN) :: TAG
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_SEND

   SUBROUTINE MPI_ISEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, IERROR)
     TYPE(*), INTENT(IN) :: BUF(..)
     INTEGER, INTENT(IN) :: COUNT
     TYPE(MPI_DATATYPE), INTENT(IN) :: DATATYPE
     INTEGER, INTENT(IN) :: DEST
     INTEGER, INTENT(IN) :: TAG
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     TYPE(MPI_REQUEST), INTENT(OUT) :: REQUEST
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_ISEND

   SUBROUTINE MPI_BSEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, IERROR)
     TYPE(*), INTENT(IN) :: BUF(..)
     INTEGER, INTENT(IN) :: COUNT
     TYPE(MPI_DATATYPE), INTENT(IN) :: DATATYPE
     INTEGER, INTENT(IN) :: DEST
     INTEGER, INTENT(IN) :: TAG
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_BSEND

   SUBROUTINE MPI_IBSEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, REQUEST, IERROR)
     TYPE(*), INTENT(IN) :: BUF(..)
     INTEGER, INTENT(IN) :: COUNT
     TYPE(MPI_DATATYPE), INTENT(IN) :: DATATYPE
     INTEGER, INTENT(IN) :: DEST
     INTEGER, INTENT(IN) :: TAG
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     TYPE(MPI_REQUEST), INTENT(OUT) :: REQUEST
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_IBSEND

   SUBROUTINE MPI_SSEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, IERROR)
     TYPE(*), INTENT(IN) :: BUF(..)
     INTEGER, INTENT(IN) :: COUNT
     TYPE(MPI_DATATYPE), INTENT(IN) :: DATATYPE
     INTEGER, INTENT(IN) :: DEST
     INTEGER, INTENT(IN) :: TAG
     TYPE(MPI_COMM), INTENT(IN) :: COMM
     INTEGER, INTENT(OUT) :: IERROR
   END SUBROUTINE MPI_SSEND

END MODULE MPI_F08

