! (C) Copyright 2005- ECMWF.
! (C) Copyright 2013- Meteo-France.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

SUBMODULE (MPL_GATHERV_MOD) MPL_GATHERV_IMPLEMENTATION_MOD

!**** MPL_GATHERV Gather data to specific processor

!     Purpose.
!     --------
!     Gather data to specific processor
!     The data may be REAL*4, REAL*8,or INTEGER, one dimensional array
!                     REAL*4,or REAL*8, two dimensional array
!                  or INTEGER scalar

!**   Interface.
!     ----------
!        CALL MPL_GATHERV

!        Input required arguments :
!        -------------------------
!           PSENDBUF -  buffer containing message
!                       (can be type REAL*4, REAL*8 or INTEGER)
!           PRECVBUF -  buffer containing message (required from kroot)
!                       (can be type REAL*4, REAL*8 or INTEGER)
!           KRECVCOUNTS-number of elements received from each process
!                       (required from kroot processor)

!        Input optional arguments :
!        -------------------------
!           KROOT    -  rank of receiveing processor (default 1)
!           KMP_TYPE -  buffering type (see MPL_BUFFER_METHOD)
!                       overrides value provided to MPL_BUFFER_METHOD
!           KCOMM    -  Communicator number if different from MPI_COMM_WORLD
!                       or from that established as the default
!                       by an MPL communicator routine
!           KRECVDISPL -displacements in PRECVBUF at which to place
!                       the incoming data
!           CDSTRING -  Character string for ABORT messages
!                       used when KERROR is not provided

!        Output required arguments :
!        -------------------------
!           none

!        Output optional arguments :
!        -------------------------
!           KREQUEST -  Communication request
!                       required when buffering type is non-blocking
!           KERROR   -  return error code.     If not supplied,
!                       MPL_GATHERV aborts when an error is detected.
!     Author.
!     -------
!        D.Dent, M.Hamrud     ECMWF

!     Modifications.
!     --------------
!        Original:  2000-11-23
!        M.Hamrud:  2014-10-22 : Add nonblocking option
!        F.Vana:    2015-03-05 : Support for single precision
!        P.Gillies: 2018-06-25 : Add SENDCOUNT argument, needed for zero-length sends
! --- *NOT* THREAD SAFE YET ---

!     ------------------------------------------------------------------

USE EC_PARKIND, ONLY : JPRD, JPIM, JPIB, JPRM
USE OML_MOD,    ONLY : OML_MY_THREAD

USE MPL_MPI,                  ONLY : MPI_COMM, MPI_DATATYPE, MPI_REQUEST, MPI_REAL4, MPI_REAL8, MPI_INTEGER, &
 &                                   MPI_CHARACTER, MPI_GATHERV, MPI_IGATHERV, MPI_COMM_SIZE
USE MPL_DATA_MODULE,          ONLY : MPL_RANK, MPL_METHOD, MPL_ERRUNIT, MPL_COMM_OML, MPL_NUMPROC, &
 &                                   JP_BLOCKING_STANDARD, JP_BLOCKING_BUFFERED, &
 &                                   JP_NON_BLOCKING_STANDARD, JP_NON_BLOCKING_BUFFERED
USE MPL_STATS_MOD,            ONLY : MPL_RECVSTATS, MPL_SENDSTATS
USE YOMMPLSTATS,              ONLY : LMPLSTATS
USE MPL_MESSAGE_MOD,          ONLY : MPL_MESSAGE
USE MPL_MYRANK_MOD,           ONLY : MPL_MYRANK
USE MPL_WAIT_MOD,             ONLY : MPL_WAIT
USE MPL_DISPLS_CONTAINER_MOD, ONLY : YDDISPLS_LIST
IMPLICIT NONE

LOGICAL            :: LLABORT=.TRUE.
REAL(KIND=JPRD)    :: ZDUM_JPRD
REAL(KIND=JPRM)    :: ZDUM_JPRM
CHARACTER          :: ZDUM_CHAR(1)
INTEGER(KIND=JPIM) :: ZDUM_INT
INTEGER(KIND=JPIM), ALLOCATABLE :: ONES(:)

CONTAINS

SUBROUTINE MPL_GATHERV_PREAMB1(IERROR,IPL_NUMPROC,IPL_MYRANK,ICOMM,IROOT,IMP_TYPE, &
  & KCOMM,KROOT,KMP_TYPE,KREQUEST)

#ifdef USE_8_BYTE_WORDS
USE MPI4TO8, ONLY : &
  MPI_COMM_SIZE => MPI_COMM_SIZE8
#endif

INTEGER(KIND=JPIM),INTENT(OUT) :: IERROR,IPL_NUMPROC,IPL_MYRANK,ICOMM,IROOT,IMP_TYPE
INTEGER(KIND=JPIM),INTENT(IN),OPTIONAL :: KROOT
INTEGER(KIND=JPIM),INTENT(IN),OPTIONAL :: KCOMM,KMP_TYPE,KREQUEST
INTEGER(KIND=JPIM) :: ITID
TYPE(MPI_COMM)     :: ICOMM_LOCAL
ITID = OML_MY_THREAD()
IERROR = 0

IF(MPL_NUMPROC < 1) CALL MPL_MESSAGE( &
  & CDMESSAGE='MPL_GATHERV: MPL NOT INITIALISED ',LDABORT=LLABORT)

IF(PRESENT(KCOMM)) THEN
  ICOMM=KCOMM
ELSE
  ICOMM=MPL_COMM_OML(ITID)
ENDIF

IF(ICOMM == MPL_COMM_OML(ITID)) THEN
  IPL_NUMPROC = MPL_NUMPROC
  IPL_MYRANK  = MPL_RANK
ELSE
  ICOMM_LOCAL%MPI_VAL=ICOMM
  CALL MPI_COMM_SIZE(ICOMM_LOCAL,IPL_NUMPROC,IERROR)
  IPL_MYRANK  = MPL_MYRANK(ICOMM)
ENDIF
IF (.NOT. ALLOCATED(ONES)) THEN
  ALLOCATE(ONES(IPL_NUMPROC))
  ONES(:) = 1_JPIM
ENDIF

IF(PRESENT(KROOT)) THEN
  IROOT=KROOT
ELSE
  IROOT=1
ENDIF

IF(PRESENT(KMP_TYPE)) THEN
  IMP_TYPE=KMP_TYPE
ELSE
  IMP_TYPE=MPL_METHOD
ENDIF
IF(IMP_TYPE == JP_NON_BLOCKING_STANDARD .OR. IMP_TYPE == JP_NON_BLOCKING_BUFFERED) THEN
  IF(.NOT.PRESENT(KREQUEST)) CALL MPL_MESSAGE(CDMESSAGE='MPL_GATHERV:  KREQUEST MISSING',LDABORT=LLABORT)
ENDIF


END SUBROUTINE MPL_GATHERV_PREAMB1

SUBROUTINE MPL_GATHERV_PREAMB2(IPL_NUMPROC,IPL_MYRANK,IRECVBUFSIZE,ISENDCOUNT,&
  & KRECVCOUNTS,KIRECVDISPL,KIRECVDISPL_PT,IMP_TYPE,KRECVDISPL,CDSTRING)

INTEGER(KIND=JPIM),INTENT(IN) :: IPL_NUMPROC,IPL_MYRANK,IRECVBUFSIZE,ISENDCOUNT
INTEGER(KIND=JPIM),INTENT(IN)  :: KRECVCOUNTS(:)
INTEGER(KIND=JPIM),ALLOCATABLE,TARGET,INTENT(OUT) :: KIRECVDISPL(:)
INTEGER(KIND=JPIM), POINTER, INTENT(OUT) :: KIRECVDISPL_PT(:)
INTEGER(KIND=JPIM),INTENT(IN) :: IMP_TYPE
INTEGER(KIND=JPIM),INTENT(IN),TARGET,OPTIONAL :: KRECVDISPL(:)
CHARACTER(LEN=*),INTENT(IN),OPTIONAL :: CDSTRING
INTEGER(KIND=JPIM) :: IR

IF(SIZE(KRECVCOUNTS)  < IPL_NUMPROC) THEN
  WRITE(MPL_ERRUNIT,*)'MPL_GATHERV: ERROR KRECVCOUNTS DIMENSION=',&
    & SIZE(KRECVCOUNTS)
  CALL MPL_MESSAGE(CDMESSAGE=&
    & 'MPL_GATHERV: ERROR KRECVCOUNTS DIMENSION IS WRONG',LDABORT=LLABORT)
ENDIF
IF(ISENDCOUNT /= KRECVCOUNTS(IPL_MYRANK)) THEN
  WRITE(MPL_ERRUNIT,*)'MPL_GATHERV: ERROR KRECVCOUNTS INCONSISTENCY ',&
    & ISENDCOUNT,KRECVCOUNTS(IPL_MYRANK)
  CALL MPL_MESSAGE(CDMESSAGE=&
    & 'MPL_GATHERV: ERROR ISENDCOUNT /= KRECVCOUNTS(MPL_RANK) ',LDABORT=LLABORT)
ENDIF

IF(PRESENT(KRECVDISPL)) THEN
  KIRECVDISPL_PT => KRECVDISPL
ELSE
  IF(IMP_TYPE == JP_NON_BLOCKING_STANDARD .OR. IMP_TYPE == JP_NON_BLOCKING_BUFFERED) THEN
    CALL YDDISPLS_LIST%APPEND(KNPROC=IPL_NUMPROC, KRECV_PT=KIRECVDISPL_PT)
  ELSE
    ALLOCATE(KIRECVDISPL(IPL_NUMPROC))
    KIRECVDISPL_PT => KIRECVDISPL
  END IF
  KIRECVDISPL_PT(1) = 0
  DO IR=2, IPL_NUMPROC
    KIRECVDISPL_PT(IR) = KIRECVDISPL_PT(IR-1) + KRECVCOUNTS(IR-1)
  ENDDO
ENDIF
DO IR=1, IPL_NUMPROC
  IF(KIRECVDISPL_PT(IR)+KRECVCOUNTS(IR) > IRECVBUFSIZE) THEN
    WRITE(MPL_ERRUNIT,'(A,4I10)')'MPL_GATHERV:RECV BUFFER TOO SMALL  ', &
      & IR,KIRECVDISPL_PT(IR),KRECVCOUNTS(IR),IRECVBUFSIZE
    CALL MPL_MESSAGE(CDMESSAGE='MPL_GATHERV',CDSTRING=CDSTRING,LDABORT=LLABORT)
  ENDIF
ENDDO

END SUBROUTINE MPL_GATHERV_PREAMB2

MODULE PROCEDURE MPL_GATHERV_REAL4

#ifdef USE_8_BYTE_WORDS
USE MPI4TO8, ONLY : &
  MPI_GATHERV => MPI_GATHERV8
#endif

INTEGER(KIND=JPIM),ALLOCATABLE :: IRECVDISPL(:)
INTEGER(KIND=JPIM),POINTER :: IRECVDISPL_PT(:)
INTEGER(KIND=JPIM) :: IERROR,IPL_NUMPROC,IPL_MYRANK,IROOT,IMP_TYPE
INTEGER(KIND=JPIM) :: IRECVBUFSIZE,ISENDCOUNT
TYPE(MPI_DATATYPE) :: IDATA_TYPE
TYPE(MPI_COMM)     :: ICOMM
TYPE(MPI_REQUEST)  :: IREQUEST_LOCAL
LOGICAL            :: LLPRESENT_RECVBUF

IDATA_TYPE=MPI_REAL4
LLPRESENT_RECVBUF=PRESENT(PRECVBUF)

#include "mpl_gatherv_realarray_tmpl.i90"

END PROCEDURE MPL_GATHERV_REAL4

MODULE PROCEDURE MPL_GATHERV_REAL8

#ifdef USE_8_BYTE_WORDS
USE MPI4TO8, ONLY : &
  MPI_GATHERV => MPI_GATHERV8
#endif

INTEGER(KIND=JPIM),ALLOCATABLE :: IRECVDISPL(:)
INTEGER(KIND=JPIM),POINTER :: IRECVDISPL_PT(:)
INTEGER(KIND=JPIM) :: IERROR,IPL_NUMPROC,IPL_MYRANK,IROOT,IMP_TYPE
INTEGER(KIND=JPIM) :: IRECVBUFSIZE,ISENDCOUNT
INTEGER(KIND=JPIM) :: IDUM,IST,IEND,JK
TYPE(MPI_DATATYPE) :: IDATA_TYPE
TYPE(MPI_COMM)     :: ICOMM
TYPE(MPI_REQUEST)  :: IREQUEST_LOCAL
LOGICAL            :: LLPRESENT_RECVBUF

IDATA_TYPE=MPI_REAL8
LLPRESENT_RECVBUF=PRESENT(PRECVBUF)

#include "mpl_gatherv_realarray_tmpl.i90"

END PROCEDURE MPL_GATHERV_REAL8

MODULE PROCEDURE MPL_GATHERV_INT

#ifdef USE_8_BYTE_WORDS
USE MPI4TO8, ONLY : &
  MPI_GATHERV => MPI_GATHERV8
#endif

INTEGER(KIND=JPIM),ALLOCATABLE :: IRECVDISPL(:)
INTEGER(KIND=JPIM),POINTER :: IRECVDISPL_PT(:)
INTEGER(KIND=JPIM) :: IERROR,IPL_NUMPROC,IPL_MYRANK,IROOT,IMP_TYPE
INTEGER(KIND=JPIM) :: IRECVBUFSIZE,ISENDCOUNT
TYPE(MPI_DATATYPE) :: IDATA_TYPE
TYPE(MPI_COMM)     :: ICOMM
TYPE(MPI_REQUEST)  :: IREQUEST_LOCAL

LOGICAL            :: LLPRESENT_RECVBUF

IDATA_TYPE=MPI_INTEGER
LLPRESENT_RECVBUF=PRESENT(KRECVBUF)

#include "mpl_gatherv_integerarray_tmpl.i90"

END PROCEDURE MPL_GATHERV_INT

MODULE PROCEDURE MPL_GATHERV_CHAR_SCALAR

#ifdef USE_8_BYTE_WORDS
USE MPI4TO8, ONLY : &
  MPI_GATHERV => MPI_GATHERV8
#endif

INTEGER(KIND=JPIM),ALLOCATABLE :: IRECVDISPL(:)
INTEGER(KIND=JPIM),POINTER :: IRECVDISPL_PT(:)
INTEGER(KIND=JPIM) :: IERROR,IPL_NUMPROC,IPL_MYRANK,IROOT,IMP_TYPE
INTEGER(KIND=JPIM) :: IRECVBUFSIZE,ISENDCOUNT
INTEGER(KIND=JPIM) :: IDUM,IST,IEND,JK !,ICOUNT
TYPE(MPI_COMM)     :: ICOMM
TYPE(MPI_REQUEST)  :: IREQUEST_LOCAL

IF(PRESENT(KSENDCOUNT)) THEN
  ISENDCOUNT=KSENDCOUNT
ELSE
  ISENDCOUNT = LEN(CSENDBUF)
ENDIF

CALL MPL_GATHERV_PREAMB1(IERROR,IPL_NUMPROC,IPL_MYRANK,ICOMM%MPI_VAL, &
 &                       IROOT,IMP_TYPE,KCOMM,KROOT,KMP_TYPE,KREQUEST)

IF(IPL_MYRANK == IROOT) THEN
  IF( .NOT. PRESENT(CRECVBUF)) CALL MPL_MESSAGE(&
    & CDMESSAGE='MPL_GATHERV:RECVBUF MISSING',CDSTRING=CDSTRING,LDABORT=LLABORT)
  IRECVBUFSIZE = LEN(CRECVBUF)*SIZE(CRECVBUF)
#ifdef MPL_CHECK_CONTIG
  IF( .NOT. IS_CONTIGUOUS(CRECVBUF) ) THEN
    CALL MPL_MESSAGE(CDMESSAGE='MPL_GATHERV: RECVBUF NOT CONTIGUOUS ',LDABORT=LLABORT)
  ENDIF
#endif
  CALL MPL_GATHERV_PREAMB2(IPL_NUMPROC,IPL_MYRANK,IRECVBUFSIZE,ISENDCOUNT,&
    & KRECVCOUNTS,IRECVDISPL,IRECVDISPL_PT,IMP_TYPE,KRECVDISPL,CDSTRING)

  IF(IMP_TYPE == JP_BLOCKING_STANDARD .OR. IMP_TYPE == JP_BLOCKING_BUFFERED) THEN
    CALL MPI_GATHERV(CSENDBUF,ISENDCOUNT,MPI_CHARACTER,CRECVBUF,KRECVCOUNTS,&
      &  IRECVDISPL_PT,MPI_CHARACTER,IROOT-1,ICOMM,IERROR)
  ELSEIF(IMP_TYPE == JP_NON_BLOCKING_STANDARD .OR. IMP_TYPE == JP_NON_BLOCKING_BUFFERED) THEN
    CALL MPI_IGATHERV(CSENDBUF,ISENDCOUNT,MPI_CHARACTER,CRECVBUF,KRECVCOUNTS,&
      &  IRECVDISPL_PT,MPI_CHARACTER,IROOT-1,ICOMM,IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
    IF(.NOT. PRESENT(KRECVDISPL)) THEN
      CALL YDDISPLS_LIST%APPEND(KREQ=KREQUEST,NO_NEW_NODE=.TRUE.)
    ENDIF
  ENDIF
  IF(LMPLSTATS) THEN
    CALL MPL_SENDSTATS(ISENDCOUNT,MPI_CHARACTER%MPI_VAL)
    CALL MPL_RECVSTATS(SUM(KRECVCOUNTS),MPI_CHARACTER%MPI_VAL)
  ENDIF
ELSE
  IF(IMP_TYPE == JP_BLOCKING_STANDARD .OR. IMP_TYPE == JP_BLOCKING_BUFFERED) THEN
    CALL MPI_GATHERV(CSENDBUF,ISENDCOUNT,MPI_CHARACTER,ZDUM_CHAR,ONES, &
      &  ONES,MPI_CHARACTER,IROOT-1,ICOMM,IERROR)
  ELSEIF(IMP_TYPE == JP_NON_BLOCKING_STANDARD .OR. IMP_TYPE == JP_NON_BLOCKING_BUFFERED) THEN
    CALL MPI_IGATHERV(CSENDBUF,ISENDCOUNT,MPI_CHARACTER,ZDUM_CHAR,ONES, &
      &  ONES,MPI_CHARACTER,IROOT-1,ICOMM,IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ENDIF
  IF(LMPLSTATS) THEN
    CALL MPL_SENDSTATS(ISENDCOUNT,MPI_CHARACTER%MPI_VAL)
  ENDIF
ENDIF

IF(PRESENT(KERROR)) THEN
  KERROR=IERROR
ELSE
  IF(IERROR /= 0 ) CALL MPL_MESSAGE( &
 &        CDMESSAGE='MPL_GATHERV',CDSTRING=CDSTRING,&
 &        KERROR=IERROR,LDABORT=LLABORT)
ENDIF

END PROCEDURE MPL_GATHERV_CHAR_SCALAR

END SUBMODULE MPL_GATHERV_IMPLEMENTATION_MOD

