! (C) Copyright 2005- ECMWF.
! (C) Copyright 2013- Meteo-France.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!

SUBMODULE (MPL_SEND_MOD) MPL_SEND_IMPLEMENTATION_MOD

USE EC_PARKIND, ONLY : JPRD, JPIM, JPIB, JPRM
USE OML_MOD,    ONLY : OML_MY_THREAD

USE MPL_MPI,         ONLY : MPI_COMM, MPI_REQUEST, MPI_REAL4, MPI_REAL8, MPI_INTEGER, MPI_INTEGER8, MPI_BYTE, &
 &                          MPI_SEND, MPI_ISEND, MPI_BSEND, MPI_IBSEND, MPI_SSEND
USE MPL_DATA_MODULE, ONLY : MPL_OUTPUT, MPL_COMM_OML, MPL_ERRUNIT, MPL_UNIT, MPL_METHOD, MPL_NUMPROC, &
 &                          JP_BLOCKING_STANDARD, JP_BLOCKING_BUFFERED, JP_BLOCKING_SYNCHRONOUS, &
 &                          JP_NON_BLOCKING_STANDARD, JP_NON_BLOCKING_BUFFERED
USE MPL_MESSAGE_MOD, ONLY : MPL_MESSAGE
USE MPL_NPROC_MOD,   ONLY : MPL_NPROC
USE MPL_STATS_MOD,   ONLY : MPL_SENDSTATS
USE YOMMPLSTATS,     ONLY : LMPLSTATS

IMPLICIT NONE

CONTAINS

MODULE PROCEDURE MPL_SEND_REAL4

#ifdef USE_8_BYTE_WORDS
  USE MPI4TO8, ONLY : &
    MPI_SEND => MPI_SEND8, MPI_BSEND => MPI_BSEND8, MPI_ISEND => MPI_ISEND8
#endif

TYPE(MPI_REQUEST)  :: IREQUEST_LOCAL
INTEGER(KIND=JPIM) :: ICOUNT,IMP_TYPE,IERROR
TYPE(MPI_COMM)     :: ICOMM
LOGICAL :: LLABORT=.TRUE.
INTEGER(KIND=JPIM) :: ITID
REAL(KIND=JPRM)    :: ZDUM(1:0)
ITID = OML_MY_THREAD()

IF(MPL_NUMPROC < 1) CALL MPL_MESSAGE( &
  & CDMESSAGE='MPL_SEND: MPL NOT INITIALISED ',LDABORT=LLABORT) 
  
IF(PRESENT(KMP_TYPE)) THEN
  IMP_TYPE=KMP_TYPE
ELSE
  IMP_TYPE=MPL_METHOD
ENDIF
IF(PRESENT(KCOMM)) THEN
  ICOMM%MPI_VAL=KCOMM
ELSE
  ICOMM%MPI_VAL=MPL_COMM_OML(ITID)
ENDIF
IF((KDEST < 1 .OR. KDEST >MPL_NPROC(ICOMM%MPI_VAL)) .AND. (.NOT. PRESENT (KCOMM))) THEN
  WRITE(MPL_ERRUNIT,*)'MPL_SEND: ERROR KDEST=',KDEST
  CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND:ILLEGAL KDEST ',LDABORT=LLABORT)
ENDIF

ICOUNT = SIZE(PBUF)
#ifdef MPL_CHECK_CONTIG
IF( .NOT. IS_CONTIGUOUS(PBUF) ) THEN
  CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND: BUFFER NOT CONTIGUOUS ',LDABORT=LLABORT)
ENDIF
#endif

IF(LMPLSTATS) THEN
  CALL MPL_SENDSTATS(ICOUNT,MPI_REAL4%MPI_VAL)
ENDIF

IF (ICOUNT == 0) THEN
  IF(IMP_TYPE == JP_BLOCKING_STANDARD) THEN
    CALL MPI_SEND(ZDUM,ICOUNT,MPI_REAL4,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE IF(IMP_TYPE == JP_BLOCKING_BUFFERED) THEN
    CALL MPI_BSEND(ZDUM,ICOUNT,MPI_REAL4,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE IF(IMP_TYPE == JP_NON_BLOCKING_STANDARD) THEN
    CALL MPI_ISEND(ZDUM,ICOUNT,MPI_REAL4,KDEST-1,KTAG,ICOMM, &
      & IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ELSE IF(IMP_TYPE == JP_NON_BLOCKING_BUFFERED) THEN
    CALL MPI_IBSEND(ZDUM,ICOUNT,MPI_REAL4,KDEST-1,KTAG,ICOMM, &
      & IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ELSE IF(IMP_TYPE == JP_BLOCKING_SYNCHRONOUS) THEN
    CALL MPI_SSEND(ZDUM,ICOUNT,MPI_REAL4,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE
    IF(PRESENT(KERROR)) THEN
      KERROR=1
    ELSE
      CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND',CDSTRING=' INVALID METHOD',KERROR=KERROR,LDABORT=LLABORT)
    ENDIF
  ENDIF
ELSE
  IF(IMP_TYPE == JP_BLOCKING_STANDARD) THEN
    CALL MPI_SEND(PBUF,ICOUNT,MPI_REAL4,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE IF(IMP_TYPE == JP_BLOCKING_BUFFERED) THEN
    CALL MPI_BSEND(PBUF,ICOUNT,MPI_REAL4,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE IF(IMP_TYPE == JP_NON_BLOCKING_STANDARD) THEN
    CALL MPI_ISEND(PBUF,ICOUNT,MPI_REAL4,KDEST-1,KTAG,ICOMM, &
      & IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ELSE IF(IMP_TYPE == JP_NON_BLOCKING_BUFFERED) THEN
    CALL MPI_IBSEND(PBUF,ICOUNT,MPI_REAL4,KDEST-1,KTAG,ICOMM, &
      & IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ELSE IF(IMP_TYPE == JP_BLOCKING_SYNCHRONOUS) THEN
    CALL MPI_SSEND(PBUF,ICOUNT,MPI_REAL4,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE
    IF(PRESENT(KERROR)) THEN
      KERROR=1
    ELSE
      CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND',CDSTRING=' INVALID METHOD',KERROR=KERROR,LDABORT=LLABORT)
    ENDIF
  ENDIF
ENDIF
IF(MPL_OUTPUT > 1 )THEN
  WRITE(MPL_UNIT,'(A,5I8)') ' MPL_SEND ',ICOUNT,IMP_TYPE,KDEST,KTAG,ICOMM
ENDIF
IF(PRESENT(KERROR)) THEN
  KERROR=IERROR
ELSE
  IF(IERROR /= 0 ) CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND',CDSTRING=CDSTRING,KERROR=IERROR,LDABORT=LLABORT)
ENDIF

END PROCEDURE MPL_SEND_REAL4  

MODULE PROCEDURE MPL_SEND_REAL8

#ifdef USE_8_BYTE_WORDS
  USE MPI4TO8, ONLY : &
    MPI_SEND => MPI_SEND8, MPI_BSEND => MPI_BSEND8, MPI_ISEND => MPI_ISEND8
#endif

TYPE(MPI_REQUEST)  :: IREQUEST_LOCAL
INTEGER(KIND=JPIM) :: ICOUNT,IMP_TYPE,IERROR
TYPE(MPI_COMM)     :: ICOMM
LOGICAL :: LLABORT=.TRUE.
INTEGER(KIND=JPIM) :: ITID
REAL(KIND=JPRD)    :: ZDUM(1:0)
ITID = OML_MY_THREAD()

IF(MPL_NUMPROC < 1) CALL MPL_MESSAGE( &
  & CDMESSAGE='MPL_SEND: MPL NOT INITIALISED ',LDABORT=LLABORT) 

IF(PRESENT(KMP_TYPE)) THEN
  IMP_TYPE=KMP_TYPE
ELSE
  IMP_TYPE=MPL_METHOD
ENDIF
IF(PRESENT(KCOMM)) THEN
  ICOMM%MPI_VAL=KCOMM
ELSE
  ICOMM%MPI_VAL=MPL_COMM_OML(ITID)
ENDIF
IF((KDEST < 1 .OR. KDEST >MPL_NPROC(ICOMM%MPI_VAL)) .AND. (.NOT. PRESENT (KCOMM))) THEN
  WRITE(MPL_ERRUNIT,*)'MPL_SEND: ERROR KDEST=',KDEST
  CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND:ILLEGAL KDEST ',LDABORT=LLABORT)
ENDIF

ICOUNT = SIZE(PBUF)
#ifdef MPL_CHECK_CONTIG
IF( .NOT. IS_CONTIGUOUS(PBUF) ) THEN
  CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND: BUFFER NOT CONTIGUOUS ',LDABORT=LLABORT)
ENDIF
#endif

IF(LMPLSTATS) THEN
  CALL MPL_SENDSTATS(ICOUNT,MPI_REAL8%MPI_VAL)
ENDIF

IF (ICOUNT == 0) THEN
  IF(IMP_TYPE == JP_BLOCKING_STANDARD) THEN
    CALL MPI_SEND(ZDUM,ICOUNT,MPI_REAL8,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE IF(IMP_TYPE == JP_BLOCKING_BUFFERED) THEN
    CALL MPI_BSEND(ZDUM,ICOUNT,MPI_REAL8,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE IF(IMP_TYPE == JP_NON_BLOCKING_STANDARD) THEN
    CALL MPI_ISEND(ZDUM,ICOUNT,MPI_REAL8,KDEST-1,KTAG,ICOMM, &
      & IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ELSE IF(IMP_TYPE == JP_NON_BLOCKING_BUFFERED) THEN
    CALL MPI_IBSEND(ZDUM,ICOUNT,MPI_REAL8,KDEST-1,KTAG,ICOMM, &
      & IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ELSE IF(IMP_TYPE == JP_BLOCKING_SYNCHRONOUS) THEN
    CALL MPI_SSEND(ZDUM,ICOUNT,MPI_REAL8,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE
    IF(PRESENT(KERROR)) THEN
      KERROR=1
    ELSE
      CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND',CDSTRING=' INVALID METHOD',KERROR=KERROR,LDABORT=LLABORT)
    ENDIF
  ENDIF
ELSE
  IF(IMP_TYPE == JP_BLOCKING_STANDARD) THEN
    CALL MPI_SEND(PBUF,ICOUNT,MPI_REAL8,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE IF(IMP_TYPE == JP_BLOCKING_BUFFERED) THEN
    CALL MPI_BSEND(PBUF,ICOUNT,MPI_REAL8,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE IF(IMP_TYPE == JP_NON_BLOCKING_STANDARD) THEN
    CALL MPI_ISEND(PBUF,ICOUNT,MPI_REAL8,KDEST-1,KTAG,ICOMM, &
      & IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ELSE IF(IMP_TYPE == JP_NON_BLOCKING_BUFFERED) THEN
    CALL MPI_IBSEND(PBUF,ICOUNT,MPI_REAL8,KDEST-1,KTAG,ICOMM, &
      & IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ELSE IF(IMP_TYPE == JP_BLOCKING_SYNCHRONOUS) THEN
    CALL MPI_SSEND(PBUF,ICOUNT,MPI_REAL8,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE
    IF(PRESENT(KERROR)) THEN
      KERROR=1
    ELSE
      CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND',CDSTRING=' INVALID METHOD',KERROR=KERROR,LDABORT=LLABORT)
    ENDIF
  ENDIF
ENDIF
IF(MPL_OUTPUT > 1 )THEN
  WRITE(MPL_UNIT,'(A,5I8)') ' MPL_SEND ',ICOUNT,IMP_TYPE,KDEST,KTAG,ICOMM
ENDIF
IF(PRESENT(KERROR)) THEN
  KERROR=IERROR
ELSE
  IF(IERROR /= 0 ) CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND',CDSTRING=CDSTRING,KERROR=IERROR,LDABORT=LLABORT)
ENDIF

END PROCEDURE MPL_SEND_REAL8

MODULE PROCEDURE MPL_SEND_INT

#ifdef USE_8_BYTE_WORDS
  USE MPI4TO8, ONLY : &
    MPI_SEND => MPI_SEND8, MPI_BSEND => MPI_BSEND8, MPI_ISEND => MPI_ISEND8
#endif

TYPE(MPI_REQUEST)  :: IREQUEST_LOCAL
INTEGER(KIND=JPIM) :: ICOUNT,IMP_TYPE,IERROR
TYPE(MPI_COMM)     :: ICOMM
LOGICAL :: LLABORT=.TRUE.
INTEGER(KIND=JPIM) :: ITID,IDUM(1:0)
ITID = OML_MY_THREAD()

IF(MPL_NUMPROC < 1) CALL MPL_MESSAGE( &
  & CDMESSAGE='MPL_SEND: MPL NOT INITIALISED ',LDABORT=LLABORT) 

IF(PRESENT(KMP_TYPE)) THEN
  IMP_TYPE=KMP_TYPE
ELSE
  IMP_TYPE=MPL_METHOD
ENDIF
IF(PRESENT(KCOMM)) THEN
  ICOMM%MPI_VAL=KCOMM
ELSE
  ICOMM%MPI_VAL=MPL_COMM_OML(ITID)
ENDIF
IF((KDEST < 1 .OR. KDEST >MPL_NPROC(ICOMM%MPI_VAL)) .AND. (.NOT. PRESENT (KCOMM))) THEN
  WRITE(MPL_ERRUNIT,*)'MPL_SEND: ERROR KDEST=',KDEST
  CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND:ILLEGAL KDEST ',LDABORT=LLABORT)
ENDIF

ICOUNT = SIZE(KBUF)
#ifdef MPL_CHECK_CONTIG
IF( .NOT. IS_CONTIGUOUS(KBUF) ) THEN
  CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND: BUFFER NOT CONTIGUOUS ',LDABORT=LLABORT)
ENDIF
#endif

IF(LMPLSTATS) THEN
  CALL MPL_SENDSTATS(ICOUNT,MPI_INTEGER%MPI_VAL)
ENDIF

IF (ICOUNT == 0) THEN
 IF(IMP_TYPE == JP_BLOCKING_STANDARD) THEN
    CALL MPI_SEND(IDUM,ICOUNT,MPI_INTEGER,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE IF(IMP_TYPE == JP_BLOCKING_BUFFERED) THEN
    CALL MPI_BSEND(IDUM,ICOUNT,MPI_INTEGER,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE IF(IMP_TYPE == JP_NON_BLOCKING_STANDARD) THEN
    CALL MPI_ISEND(IDUM,ICOUNT,MPI_INTEGER,KDEST-1,KTAG,ICOMM, &
      & IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ELSE IF(IMP_TYPE == JP_NON_BLOCKING_BUFFERED) THEN
    CALL MPI_IBSEND(IDUM,ICOUNT,MPI_INTEGER,KDEST-1,KTAG,ICOMM, &
      & IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ELSE IF(IMP_TYPE == JP_BLOCKING_SYNCHRONOUS) THEN
    CALL MPI_SSEND(IDUM,ICOUNT,MPI_INTEGER,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE
    IF(PRESENT(KERROR)) THEN
      KERROR=1
    ELSE
      CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND',CDSTRING=' INVALID METHOD',KERROR=KERROR,LDABORT=LLABORT)
    ENDIF
  ENDIF
ELSE
  IF(IMP_TYPE == JP_BLOCKING_STANDARD) THEN
    CALL MPI_SEND(KBUF,ICOUNT,MPI_INTEGER,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE IF(IMP_TYPE == JP_BLOCKING_BUFFERED) THEN
    CALL MPI_BSEND(KBUF,ICOUNT,MPI_INTEGER,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE IF(IMP_TYPE == JP_NON_BLOCKING_STANDARD) THEN
    CALL MPI_ISEND(KBUF,ICOUNT,MPI_INTEGER,KDEST-1,KTAG,ICOMM, &
      & IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ELSE IF(IMP_TYPE == JP_NON_BLOCKING_BUFFERED) THEN
    CALL MPI_IBSEND(KBUF,ICOUNT,MPI_INTEGER,KDEST-1,KTAG,ICOMM, &
      & IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ELSE IF(IMP_TYPE == JP_BLOCKING_SYNCHRONOUS) THEN
    CALL MPI_SSEND(KBUF,ICOUNT,MPI_INTEGER,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE
    IF(PRESENT(KERROR)) THEN
      KERROR=1
    ELSE
      CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND',CDSTRING=' INVALID METHOD',KERROR=KERROR,LDABORT=LLABORT)
    ENDIF
  ENDIF
ENDIF
IF(MPL_OUTPUT > 1 )THEN
  WRITE(MPL_UNIT,'(A,5I8)') ' MPL_SEND ',ICOUNT,IMP_TYPE,KDEST,KTAG,ICOMM
ENDIF
IF(PRESENT(KERROR)) THEN
  KERROR=IERROR
ELSE
  IF(IERROR /= 0 ) CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND',CDSTRING=CDSTRING,KERROR=IERROR,LDABORT=LLABORT)
ENDIF

END PROCEDURE MPL_SEND_INT


MODULE PROCEDURE MPL_SEND_INT8

#ifdef USE_8_BYTE_WORDS
  USE MPI4TO8, ONLY : &
    MPI_SEND => MPI_SEND8, MPI_BSEND => MPI_BSEND8, MPI_ISEND => MPI_ISEND8
#endif

TYPE(MPI_REQUEST)  :: IREQUEST_LOCAL
INTEGER(KIND=JPIM) :: ICOUNT,IMP_TYPE,IERROR
TYPE(MPI_COMM)     :: ICOMM
LOGICAL            :: LLABORT=.TRUE.
INTEGER(KIND=JPIM) :: ITID
INTEGER(KIND=JPIB) :: IDUM(1:0)
ITID = OML_MY_THREAD()

IF(MPL_NUMPROC < 1) CALL MPL_MESSAGE( &
  & CDMESSAGE='MPL_SEND: MPL NOT INITIALISED ',LDABORT=LLABORT) 

IF(PRESENT(KMP_TYPE)) THEN
  IMP_TYPE=KMP_TYPE
ELSE
  IMP_TYPE=MPL_METHOD
ENDIF
IF(PRESENT(KCOMM)) THEN
  ICOMM%MPI_VAL=KCOMM
ELSE
  ICOMM%MPI_VAL=MPL_COMM_OML(ITID)
ENDIF
IF((KDEST < 1 .OR. KDEST >MPL_NPROC(ICOMM%MPI_VAL)) .AND. (.NOT. PRESENT (KCOMM))) THEN
  WRITE(MPL_ERRUNIT,*)'MPL_SEND: ERROR KDEST=',KDEST
  CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND:ILLEGAL KDEST ',LDABORT=LLABORT)
ENDIF

ICOUNT = SIZE(KBUF)
#ifdef MPL_CHECK_CONTIG
IF( .NOT. IS_CONTIGUOUS(KBUF) ) THEN
  CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND: BUFFER NOT CONTIGUOUS ',LDABORT=LLABORT)
ENDIF
#endif
IF(LMPLSTATS) THEN
  CALL MPL_SENDSTATS(ICOUNT,MPI_INTEGER8%MPI_VAL)
ENDIF

IF (ICOUNT == 0) THEN
  IF(IMP_TYPE == JP_BLOCKING_STANDARD) THEN
    CALL MPI_SEND(IDUM,ICOUNT,MPI_INTEGER8,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE IF(IMP_TYPE == JP_BLOCKING_BUFFERED) THEN
    CALL MPI_BSEND(IDUM,ICOUNT,MPI_INTEGER8,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE IF(IMP_TYPE == JP_NON_BLOCKING_STANDARD) THEN
    CALL MPI_ISEND(IDUM,ICOUNT,MPI_INTEGER8,KDEST-1,KTAG,ICOMM, &
      & IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ELSE IF(IMP_TYPE == JP_NON_BLOCKING_BUFFERED) THEN
    CALL MPI_IBSEND(IDUM,ICOUNT,MPI_INTEGER8,KDEST-1,KTAG,ICOMM, &
      & IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ELSE IF(IMP_TYPE == JP_BLOCKING_SYNCHRONOUS) THEN
    CALL MPI_SSEND(IDUM,ICOUNT,MPI_INTEGER8,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE
    IF(PRESENT(KERROR)) THEN
      KERROR=1
    ELSE
      CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND',CDSTRING=' INVALID METHOD',KERROR=KERROR,LDABORT=LLABORT)
    ENDIF
  ENDIF
ELSE
  IF(IMP_TYPE == JP_BLOCKING_STANDARD) THEN
    CALL MPI_SEND(KBUF,ICOUNT,MPI_INTEGER8,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE IF(IMP_TYPE == JP_BLOCKING_BUFFERED) THEN
    CALL MPI_BSEND(KBUF,ICOUNT,MPI_INTEGER8,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE IF(IMP_TYPE == JP_NON_BLOCKING_STANDARD) THEN
    CALL MPI_ISEND(KBUF,ICOUNT,MPI_INTEGER8,KDEST-1,KTAG,ICOMM, &
      & IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ELSE IF(IMP_TYPE == JP_NON_BLOCKING_BUFFERED) THEN
    CALL MPI_IBSEND(KBUF,ICOUNT,MPI_INTEGER8,KDEST-1,KTAG,ICOMM, &
      & IREQUEST_LOCAL,IERROR)
    KREQUEST=IREQUEST_LOCAL%MPI_VAL
  ELSE IF(IMP_TYPE == JP_BLOCKING_SYNCHRONOUS) THEN
    CALL MPI_SSEND(KBUF,ICOUNT,MPI_INTEGER8,KDEST-1,KTAG,ICOMM,IERROR)
  ELSE
    IF(PRESENT(KERROR)) THEN
      KERROR=1
    ELSE
      CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND',CDSTRING=' INVALID METHOD',KERROR=KERROR,LDABORT=LLABORT)
    ENDIF
  ENDIF
ENDIF
IF(MPL_OUTPUT > 1 )THEN
  WRITE(MPL_UNIT,'(A,5I8)') ' MPL_SEND ',ICOUNT,IMP_TYPE,KDEST,KTAG,ICOMM
ENDIF
IF(PRESENT(KERROR)) THEN
  KERROR=IERROR
ELSE
  IF(IERROR /= 0 ) CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND',CDSTRING=CDSTRING,KERROR=IERROR,LDABORT=LLABORT)
ENDIF

END PROCEDURE MPL_SEND_INT8

MODULE PROCEDURE MPL_SEND_CHAR_SCALAR

#ifdef USE_8_BYTE_WORDS
  USE MPI4TO8, ONLY : &
    MPI_SEND => MPI_SEND8, MPI_BSEND => MPI_BSEND8, MPI_ISEND => MPI_ISEND8
#endif

TYPE(MPI_REQUEST)  :: IREQUEST_LOCAL
INTEGER(KIND=JPIM) :: ICOUNT,IMP_TYPE,IERROR
TYPE(MPI_COMM)     :: ICOMM
LOGICAL :: LLABORT=.TRUE.
INTEGER(KIND=JPIM) :: ITID
ITID = OML_MY_THREAD()

IF(MPL_NUMPROC < 1) CALL MPL_MESSAGE( &
  & CDMESSAGE='MPL_SEND: MPL NOT INITIALISED ',LDABORT=LLABORT) 

IF(PRESENT(KMP_TYPE)) THEN
  IMP_TYPE=KMP_TYPE
ELSE
  IMP_TYPE=MPL_METHOD
ENDIF
IF(PRESENT(KCOMM)) THEN
  ICOMM%MPI_VAL=KCOMM
ELSE
  ICOMM%MPI_VAL=MPL_COMM_OML(ITID)
ENDIF
IF((KDEST < 1 .OR. KDEST >MPL_NPROC(ICOMM%MPI_VAL)) .AND. (.NOT. PRESENT (KCOMM))) THEN
  WRITE(MPL_ERRUNIT,*)'MPL_SEND: ERROR KDEST=',KDEST
  CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND:ILLEGAL KDEST ',LDABORT=LLABORT)
ENDIF

ICOUNT = LEN(CDCHAR)

IF(LMPLSTATS) THEN
  CALL MPL_SENDSTATS(ICOUNT,MPI_BYTE%MPI_VAL)
ENDIF

IF(IMP_TYPE == JP_BLOCKING_STANDARD) THEN
  CALL MPI_SEND(CDCHAR,ICOUNT,MPI_BYTE,KDEST-1,KTAG,ICOMM,IERROR)
ELSE IF(IMP_TYPE == JP_BLOCKING_BUFFERED) THEN
  CALL MPI_BSEND(CDCHAR,ICOUNT,MPI_BYTE,KDEST-1,KTAG,ICOMM,IERROR)
ELSE IF(IMP_TYPE == JP_NON_BLOCKING_STANDARD) THEN
  CALL MPI_ISEND(CDCHAR,ICOUNT,MPI_BYTE,KDEST-1,KTAG,ICOMM, &
    & IREQUEST_LOCAL,IERROR)
  KREQUEST=IREQUEST_LOCAL%MPI_VAL
ELSE IF(IMP_TYPE == JP_NON_BLOCKING_BUFFERED) THEN
  CALL MPI_IBSEND(CDCHAR,ICOUNT,MPI_BYTE,KDEST-1,KTAG,ICOMM, &
    & IREQUEST_LOCAL,IERROR)
  KREQUEST=IREQUEST_LOCAL%MPI_VAL
ELSE IF(IMP_TYPE == JP_BLOCKING_SYNCHRONOUS) THEN
  CALL MPI_SSEND(CDCHAR,ICOUNT,MPI_BYTE,KDEST-1,KTAG,ICOMM,IERROR)
ELSE
  IF(PRESENT(KERROR)) THEN
    KERROR=1
  ELSE
    CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND',CDSTRING=' INVALID METHOD',KERROR=KERROR,LDABORT=LLABORT)
  ENDIF
ENDIF
IF(MPL_OUTPUT > 1 )THEN
  WRITE(MPL_UNIT,'(A,5I8)') ' MPL_SEND ',ICOUNT,IMP_TYPE,KDEST,KTAG,ICOMM
ENDIF
IF(PRESENT(KERROR)) THEN
  KERROR=IERROR
ELSE
  IF(IERROR /= 0 ) CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND',CDSTRING=CDSTRING,KERROR=IERROR,LDABORT=LLABORT)
ENDIF

END PROCEDURE MPL_SEND_CHAR_SCALAR

MODULE PROCEDURE MPL_SEND_CHAR

#ifdef USE_8_BYTE_WORDS
  USE MPI4TO8, ONLY : &
    MPI_SEND => MPI_SEND8, MPI_BSEND => MPI_BSEND8, MPI_ISEND => MPI_ISEND8
#endif

TYPE(MPI_REQUEST)  :: IREQUEST_LOCAL
INTEGER(KIND=JPIM) :: ICOUNT,IMP_TYPE,IERROR
TYPE(MPI_COMM)     :: ICOMM
LOGICAL            :: LLABORT=.TRUE.
INTEGER(KIND=JPIM) :: ITID
ITID = OML_MY_THREAD()

IF(MPL_NUMPROC < 1) CALL MPL_MESSAGE( &
  & CDMESSAGE='MPL_SEND: MPL NOT INITIALISED ',LDABORT=LLABORT) 

IF(PRESENT(KMP_TYPE)) THEN
  IMP_TYPE=KMP_TYPE
ELSE
  IMP_TYPE=MPL_METHOD
ENDIF
IF(PRESENT(KCOMM)) THEN
  ICOMM%MPI_VAL=KCOMM
ELSE
  ICOMM%MPI_VAL=MPL_COMM_OML(ITID)
ENDIF
IF((KDEST < 1 .OR. KDEST >MPL_NPROC(ICOMM%MPI_VAL)) .AND. (.NOT. PRESENT (KCOMM))) THEN
  WRITE(MPL_ERRUNIT,*)'MPL_SEND: ERROR KDEST=',KDEST
  CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND:ILLEGAL KDEST ',LDABORT=LLABORT)
ENDIF

ICOUNT = LEN(CDCHAR) * SIZE(CDCHAR)

IF(LMPLSTATS) THEN
  CALL MPL_SENDSTATS(ICOUNT,MPI_BYTE%MPI_VAL)
ENDIF

IF(IMP_TYPE == JP_BLOCKING_STANDARD) THEN
  CALL MPI_SEND(CDCHAR,ICOUNT,MPI_BYTE,KDEST-1,KTAG,ICOMM,IERROR)
ELSE IF(IMP_TYPE == JP_BLOCKING_BUFFERED) THEN
  CALL MPI_BSEND(CDCHAR,ICOUNT,MPI_BYTE,KDEST-1,KTAG,ICOMM,IERROR)
ELSE IF(IMP_TYPE == JP_NON_BLOCKING_STANDARD) THEN
  CALL MPI_ISEND(CDCHAR,ICOUNT,MPI_BYTE,KDEST-1,KTAG,ICOMM, &
    & IREQUEST_LOCAL,IERROR)
  KREQUEST=IREQUEST_LOCAL%MPI_VAL
ELSE IF(IMP_TYPE == JP_NON_BLOCKING_BUFFERED) THEN
  CALL MPI_IBSEND(CDCHAR,ICOUNT,MPI_BYTE,KDEST-1,KTAG,ICOMM, &
    & IREQUEST_LOCAL,IERROR)
  KREQUEST=IREQUEST_LOCAL%MPI_VAL
ELSE IF(IMP_TYPE == JP_BLOCKING_SYNCHRONOUS) THEN
  CALL MPI_SSEND(CDCHAR,ICOUNT,MPI_BYTE,KDEST-1,KTAG,ICOMM,IERROR)
ELSE
  IF(PRESENT(KERROR)) THEN
    KERROR=1
  ELSE
    CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND',CDSTRING=' INVALID METHOD',KERROR=KERROR,LDABORT=LLABORT)
  ENDIF
ENDIF
IF(MPL_OUTPUT > 1 )THEN
  WRITE(MPL_UNIT,'(A,5I8)') ' MPL_SEND ',ICOUNT,IMP_TYPE,KDEST,KTAG,ICOMM
ENDIF
IF(PRESENT(KERROR)) THEN
  KERROR=IERROR
ELSE
  IF(IERROR /= 0 ) CALL MPL_MESSAGE(CDMESSAGE='MPL_SEND',CDSTRING=CDSTRING,KERROR=IERROR,LDABORT=LLABORT)
ENDIF

END PROCEDURE MPL_SEND_CHAR

END SUBMODULE MPL_SEND_IMPLEMENTATION_MOD
