! (C) Copyright 2026- ECMWF.
! (C) Copyright 2026- Meteo-France.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE TEST_MPL_ALLOCATOR
USE EC_PARKIND, ONLY: JPIM, JPIB, JPRD, JPRM
USE MPL_ALLOCATOR_MOD, ONLY : MPL_ALLOCATOR_INIT, MPL_ALLOCATOR_FINAL, MPL_ALLOCATOR_INITIALIZED, &
                            & MPL_ALLOCATE, MPL_DEALLOCATE, MPL_RESOURCE, &
                            & MPL_ALLOCATOR_RESERVE, MPL_ALLOCATOR_CAPACITY, MPL_ALLOCATOR_ALLOCATED
IMPLICIT NONE
PUBLIC
CONTAINS

SUBROUTINE FAIL(MSG)
    USE MPL_ABORT_MOD, ONLY : MPL_ABORT
    CHARACTER(LEN=*), INTENT(IN) :: MSG
    CALL MPL_ABORT(MSG)
END SUBROUTINE

SUBROUTINE WARN(MSG)
    USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : ERROR_UNIT
    CHARACTER(LEN=*), INTENT(IN) :: MSG
    WRITE(ERROR_UNIT,'(A,A)') "WARNING: ",MSG
END SUBROUTINE

FUNCTION GET_EXPECTED_RESOURCE_FROM_ENV() RESULT(CMPL_RESOURCE)
    CHARACTER(LEN=512) :: CMPL_RESOURCE
    CALL GET_ENVIRONMENT_VARIABLE("EXPECTED_MPL_RESOURCE",CMPL_RESOURCE)
END FUNCTION

SUBROUTINE CHECK_MPL_RESOURCE_IS_EXPECTED(EXPECTED_RESOURCE)
    IMPLICIT NONE
    CHARACTER(LEN=*), INTENT(IN), OPTIONAL :: EXPECTED_RESOURCE
    CHARACTER(LEN=256) :: CLEXPECTED_RESOURCE
    IF (PRESENT(EXPECTED_RESOURCE)) THEN
        CLEXPECTED_RESOURCE = EXPECTED_RESOURCE
    ELSE
        CLEXPECTED_RESOURCE = GET_EXPECTED_RESOURCE_FROM_ENV()
    ENDIF
    IF (LEN_TRIM(CLEXPECTED_RESOURCE) > 0) THEN
        IF (MPL_RESOURCE() /= CLEXPECTED_RESOURCE) THEN
            CALL FAIL("Expected: MPL_RESOURCE() == "//TRIM(CLEXPECTED_RESOURCE)//" whereas MPL_RESOURCE() == "&
                     &//TRIM(MPL_RESOURCE()))
        ENDIF
    ENDIF
END SUBROUTINE

SUBROUTINE CHECK_MPL_ALLOCATOR_IS_INITIALIZED(EXPECTED)
    IMPLICIT NONE
    LOGICAL, INTENT(IN) :: EXPECTED
    IF (MPL_ALLOCATOR_INITIALIZED() .NEQV. EXPECTED) THEN
        IF (EXPECTED) THEN
            CALL FAIL("Expected: MPL_ALLOCATOR_INITIALIZED() == .TRUE.")
        ELSE
            CALL FAIL("Expected: MPL_ALLOCATOR_INITIALIZED() == .FALSE.")
        ENDIF
    ENDIF
END SUBROUTINE

!----------------------------------------------------------------------------------------------------------------------------------

SUBROUTINE VARIOUS_ALLOCATIONS_WITH_SHAPE
    IMPLICIT NONE
    REAL(JPRD),    POINTER :: ARRAY_JPRD_1D(:), ARRAY_JPRD_2D(:,:), ARRAY_JPRD_3D(:,:,:), ARRAY_JPRD_4D(:,:,:,:)
    REAL(JPRM),    POINTER :: ARRAY_JPRM_1D(:), ARRAY_JPRM_2D(:,:), ARRAY_JPRM_3D(:,:,:), ARRAY_JPRM_4D(:,:,:,:)
    INTEGER(JPIM), POINTER :: ARRAY_JPIM_1D(:), ARRAY_JPIM_2D(:,:), ARRAY_JPIM_3D(:,:,:), ARRAY_JPIM_4D(:,:,:,:)
    INTEGER(JPIB), POINTER :: ARRAY_JPIB_1D(:), ARRAY_JPIB_2D(:,:), ARRAY_JPIB_3D(:,:,:), ARRAY_JPIB_4D(:,:,:,:)

    CALL MPL_ALLOCATE("ARRAY_JPRD_1D", ARRAY_JPRD_1D, SHAPE=[100])
    CALL MPL_ALLOCATE("ARRAY_JPRM_1D", ARRAY_JPRM_1D, SHAPE=[100])
    CALL MPL_ALLOCATE("ARRAY_JPIM_1D", ARRAY_JPIM_1D, SHAPE=[100])
    CALL MPL_ALLOCATE("ARRAY_JPIB_1D", ARRAY_JPIB_1D, SHAPE=[100])

    CALL MPL_ALLOCATE("ARRAY_JPRD_2D", ARRAY_JPRD_2D, SHAPE=[32,100])
    CALL MPL_ALLOCATE("ARRAY_JPRM_2D", ARRAY_JPRM_2D, SHAPE=[32,100])
    CALL MPL_ALLOCATE("ARRAY_JPIM_2D", ARRAY_JPIM_2D, SHAPE=[32,100])
    CALL MPL_ALLOCATE("ARRAY_JPIB_2D", ARRAY_JPIB_2D, SHAPE=[32,100])

    CALL MPL_ALLOCATE("ARRAY_JPRD_3D", ARRAY_JPRD_3D, SHAPE=[32,137,100])
    CALL MPL_ALLOCATE("ARRAY_JPRM_3D", ARRAY_JPRM_3D, SHAPE=[32,137,100])
    CALL MPL_ALLOCATE("ARRAY_JPIM_3D", ARRAY_JPIM_3D, SHAPE=[32,137,100])
    CALL MPL_ALLOCATE("ARRAY_JPIB_3D", ARRAY_JPIB_3D, SHAPE=[32,137,100])

    CALL MPL_ALLOCATE("ARRAY_JPRD_4D", ARRAY_JPRD_4D, SHAPE=[32,137,8,100])
    CALL MPL_ALLOCATE("ARRAY_JPRM_4D", ARRAY_JPRM_4D, SHAPE=[32,137,8,100])
    CALL MPL_ALLOCATE("ARRAY_JPIM_4D", ARRAY_JPIM_4D, SHAPE=[32,137,8,100])
    CALL MPL_ALLOCATE("ARRAY_JPIB_4D", ARRAY_JPIB_4D, SHAPE=[32,137,8,100])

    WRITE(0,'(A,F0.2,A)') "ALLOCATED AFTER MPL_ALLOCATE: ", REAL(MPL_ALLOCATOR_ALLOCATED(),JPRD)/(1024*1024),"MB"

    CALL MPL_DEALLOCATE("ARRAY_JPRD_1D", ARRAY_JPRD_1D)
    CALL MPL_DEALLOCATE("ARRAY_JPRM_1D", ARRAY_JPRM_1D)
    CALL MPL_DEALLOCATE("ARRAY_JPIM_1D", ARRAY_JPIM_1D)
    CALL MPL_DEALLOCATE("ARRAY_JPIB_1D", ARRAY_JPIB_1D)

    CALL MPL_DEALLOCATE("ARRAY_JPRD_2D", ARRAY_JPRD_2D)
    CALL MPL_DEALLOCATE("ARRAY_JPRM_2D", ARRAY_JPRM_2D)
    CALL MPL_DEALLOCATE("ARRAY_JPIM_2D", ARRAY_JPIM_2D)
    CALL MPL_DEALLOCATE("ARRAY_JPIB_2D", ARRAY_JPIB_2D)

    CALL MPL_DEALLOCATE("ARRAY_JPRD_3D", ARRAY_JPRD_3D)
    CALL MPL_DEALLOCATE("ARRAY_JPRM_3D", ARRAY_JPRM_3D)
    CALL MPL_DEALLOCATE("ARRAY_JPIM_3D", ARRAY_JPIM_3D)
    CALL MPL_DEALLOCATE("ARRAY_JPIB_3D", ARRAY_JPIB_3D)

    CALL MPL_DEALLOCATE("ARRAY_JPRD_4D", ARRAY_JPRD_4D)
    CALL MPL_DEALLOCATE("ARRAY_JPRM_4D", ARRAY_JPRM_4D)
    CALL MPL_DEALLOCATE("ARRAY_JPIM_4D", ARRAY_JPIM_4D)
    CALL MPL_DEALLOCATE("ARRAY_JPIB_4D", ARRAY_JPIB_4D)

    WRITE(0,'(A,F0.2,A)') "ALLOCATED AFTER MPL_DEALLOCATE: ", REAL(MPL_ALLOCATOR_ALLOCATED(),JPRD)/(1024*1024),"MB"

END SUBROUTINE

!----------------------------------------------------------------------------------------------------------------------------------

SUBROUTINE VARIOUS_ALLOCATIONS_WITH_BOUNDS
    IMPLICIT NONE
    REAL(JPRD),    POINTER :: ARRAY_JPRD_1D(:), ARRAY_JPRD_2D(:,:), ARRAY_JPRD_3D(:,:,:), ARRAY_JPRD_4D(:,:,:,:)
    REAL(JPRM),    POINTER :: ARRAY_JPRM_1D(:), ARRAY_JPRM_2D(:,:), ARRAY_JPRM_3D(:,:,:), ARRAY_JPRM_4D(:,:,:,:)
    INTEGER(JPIM), POINTER :: ARRAY_JPIM_1D(:), ARRAY_JPIM_2D(:,:), ARRAY_JPIM_3D(:,:,:), ARRAY_JPIM_4D(:,:,:,:)
    INTEGER(JPIB), POINTER :: ARRAY_JPIB_1D(:), ARRAY_JPIB_2D(:,:), ARRAY_JPIB_3D(:,:,:), ARRAY_JPIB_4D(:,:,:,:)

    CALL MPL_ALLOCATE("ARRAY_JPRD_1D", ARRAY_JPRD_1D, LBOUNDS=[0], UBOUNDS=[99])
    CALL MPL_ALLOCATE("ARRAY_JPRM_1D", ARRAY_JPRM_1D, LBOUNDS=[0], UBOUNDS=[99])
    CALL MPL_ALLOCATE("ARRAY_JPIM_1D", ARRAY_JPIM_1D, LBOUNDS=[0], UBOUNDS=[99])
    CALL MPL_ALLOCATE("ARRAY_JPIB_1D", ARRAY_JPIB_1D, LBOUNDS=[0], UBOUNDS=[99])

    CALL MPL_ALLOCATE("ARRAY_JPRD_2D", ARRAY_JPRD_2D, LBOUNDS=[0,0], UBOUNDS=[31,99])
    CALL MPL_ALLOCATE("ARRAY_JPRM_2D", ARRAY_JPRM_2D, LBOUNDS=[0,0], UBOUNDS=[31,99])
    CALL MPL_ALLOCATE("ARRAY_JPIM_2D", ARRAY_JPIM_2D, LBOUNDS=[0,0], UBOUNDS=[31,99])
    CALL MPL_ALLOCATE("ARRAY_JPIB_2D", ARRAY_JPIB_2D, LBOUNDS=[0,0], UBOUNDS=[31,99])

    CALL MPL_ALLOCATE("ARRAY_JPRD_3D", ARRAY_JPRD_3D, LBOUNDS=[0,0,0], UBOUNDS=[31,136,99])
    CALL MPL_ALLOCATE("ARRAY_JPRM_3D", ARRAY_JPRM_3D, LBOUNDS=[0,0,0], UBOUNDS=[31,136,99])
    CALL MPL_ALLOCATE("ARRAY_JPIM_3D", ARRAY_JPIM_3D, LBOUNDS=[0,0,0], UBOUNDS=[31,136,99])
    CALL MPL_ALLOCATE("ARRAY_JPIB_3D", ARRAY_JPIB_3D, LBOUNDS=[0,0,0], UBOUNDS=[31,136,99])

    CALL MPL_ALLOCATE("ARRAY_JPRD_4D", ARRAY_JPRD_4D, LBOUNDS=[0,0,0,0], UBOUNDS=[31,136,7,99])
    CALL MPL_ALLOCATE("ARRAY_JPRM_4D", ARRAY_JPRM_4D, LBOUNDS=[0,0,0,0], UBOUNDS=[31,136,7,99])
    CALL MPL_ALLOCATE("ARRAY_JPIM_4D", ARRAY_JPIM_4D, LBOUNDS=[0,0,0,0], UBOUNDS=[31,136,7,99])
    CALL MPL_ALLOCATE("ARRAY_JPIB_4D", ARRAY_JPIB_4D, LBOUNDS=[0,0,0,0], UBOUNDS=[31,136,7,99])

    WRITE(0,'(A,F0.2,A)') "ALLOCATED AFTER MPL_ALLOCATE: ", REAL(MPL_ALLOCATOR_ALLOCATED(),JPRD)/(1024*1024),"MB"

    CALL MPL_DEALLOCATE("ARRAY_JPRD_1D", ARRAY_JPRD_1D)
    CALL MPL_DEALLOCATE("ARRAY_JPRM_1D", ARRAY_JPRM_1D)
    CALL MPL_DEALLOCATE("ARRAY_JPIM_1D", ARRAY_JPIM_1D)
    CALL MPL_DEALLOCATE("ARRAY_JPIB_1D", ARRAY_JPIB_1D)

    CALL MPL_DEALLOCATE("ARRAY_JPRD_2D", ARRAY_JPRD_2D)
    CALL MPL_DEALLOCATE("ARRAY_JPRM_2D", ARRAY_JPRM_2D)
    CALL MPL_DEALLOCATE("ARRAY_JPIM_2D", ARRAY_JPIM_2D)
    CALL MPL_DEALLOCATE("ARRAY_JPIB_2D", ARRAY_JPIB_2D)

    CALL MPL_DEALLOCATE("ARRAY_JPRD_3D", ARRAY_JPRD_3D)
    CALL MPL_DEALLOCATE("ARRAY_JPRM_3D", ARRAY_JPRM_3D)
    CALL MPL_DEALLOCATE("ARRAY_JPIM_3D", ARRAY_JPIM_3D)
    CALL MPL_DEALLOCATE("ARRAY_JPIB_3D", ARRAY_JPIB_3D)

    CALL MPL_DEALLOCATE("ARRAY_JPRD_4D", ARRAY_JPRD_4D)
    CALL MPL_DEALLOCATE("ARRAY_JPRM_4D", ARRAY_JPRM_4D)
    CALL MPL_DEALLOCATE("ARRAY_JPIM_4D", ARRAY_JPIM_4D)
    CALL MPL_DEALLOCATE("ARRAY_JPIB_4D", ARRAY_JPIB_4D)

    WRITE(0,'(A,F0.2,A)') "ALLOCATED AFTER MPL_DEALLOCATE: ", REAL(MPL_ALLOCATOR_ALLOCATED(),JPRD)/(1024*1024),"MB"

END SUBROUTINE

!----------------------------------------------------------------------------------------------------------------------------------

SUBROUTINE TEST_NO_INIT()
    IMPLICIT NONE
    CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
    IF (MPL_ALLOCATOR_ALLOCATED() /= 0) CALL WARN("Expected: MPL_ALLOCATOR_ALLOCATED() == 0")
    IF (MPL_ALLOCATOR_CAPACITY() == 0 .AND. MPL_ALLOCATOR_CAPACITY() /= -1) CALL WARN("Expected: MPL_ALLOCATOR_CAPACITY() > 0")
    CALL VARIOUS_ALLOCATIONS_WITH_SHAPE
    CALL VARIOUS_ALLOCATIONS_WITH_BOUNDS
    IF (MPL_ALLOCATOR_ALLOCATED() /= 0 ) CALL WARN("Expected: MPL_ALLOCATOR_ALLOCATED() == 0")
    CALL CHECK_MPL_RESOURCE_IS_EXPECTED("FORTRAN")
    CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
END SUBROUTINE TEST_NO_INIT

!----------------------------------------------------------------------------------------------------------------------------------

SUBROUTINE TEST_INIT_NO_SIZE(RESOURCE)
    IMPLICIT NONE
    CHARACTER(LEN=*), INTENT(IN), OPTIONAL :: RESOURCE
    CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
    IF (PRESENT(RESOURCE)) THEN
        CALL MPL_ALLOCATOR_INIT(RESOURCE=RESOURCE)
        CALL CHECK_MPL_RESOURCE_IS_EXPECTED(RESOURCE)
    ELSE
        CALL MPL_ALLOCATOR_INIT()
        CALL CHECK_MPL_RESOURCE_IS_EXPECTED()
    ENDIF
    CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.TRUE.)

    IF (MPL_ALLOCATOR_ALLOCATED() /= 0) CALL WARN("Expected: MPL_ALLOCATOR_ALLOCATED() == 0")
    CALL VARIOUS_ALLOCATIONS_WITH_SHAPE
    CALL VARIOUS_ALLOCATIONS_WITH_BOUNDS
    IF (MPL_ALLOCATOR_ALLOCATED() /= 0 ) CALL WARN("Expected: MPL_ALLOCATOR_ALLOCATED() == 0")
    CALL MPL_ALLOCATOR_FINAL()
END SUBROUTINE TEST_INIT_NO_SIZE

!----------------------------------------------------------------------------------------------------------------------------------

SUBROUTINE TEST_INIT_SIZE(RESOURCE)
    IMPLICIT NONE
    CHARACTER(LEN=*), INTENT(IN), OPTIONAL :: RESOURCE
    CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
    IF (PRESENT(RESOURCE)) THEN
        CALL MPL_ALLOCATOR_INIT(RESOURCE=RESOURCE, SIZE=INT(1024*1024,JPIB))
        CALL CHECK_MPL_RESOURCE_IS_EXPECTED(RESOURCE)
    ELSE
        CALL MPL_ALLOCATOR_INIT(SIZE=INT(1024*1024,JPIB))
        CALL CHECK_MPL_RESOURCE_IS_EXPECTED()
    ENDIF
    CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.TRUE.)
    IF (MPL_ALLOCATOR_ALLOCATED() /= 0) CALL WARN("Expected: MPL_ALLOCATOR_ALLOCATED() == 0")
    IF (MPL_ALLOCATOR_CAPACITY() == 0 .AND. MPL_ALLOCATOR_CAPACITY() /= -1) CALL WARN("Expected: MPL_ALLOCATOR_CAPACITY() > 0")
    CALL VARIOUS_ALLOCATIONS_WITH_SHAPE
    CALL VARIOUS_ALLOCATIONS_WITH_BOUNDS
    IF (MPL_ALLOCATOR_ALLOCATED() /= 0 ) CALL WARN("Expected: MPL_ALLOCATOR_ALLOCATED() == 0")
    CALL MPL_ALLOCATOR_FINAL()
END SUBROUTINE TEST_INIT_SIZE

!----------------------------------------------------------------------------------------------------------------------------------

SUBROUTINE TEST_INIT_AND_RESERVE(RESOURCE)
    IMPLICIT NONE
    CHARACTER(LEN=*), INTENT(IN), OPTIONAL :: RESOURCE
    CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
    IF (PRESENT(RESOURCE)) THEN
        CALL MPL_ALLOCATOR_INIT(RESOURCE=RESOURCE)
        CALL CHECK_MPL_RESOURCE_IS_EXPECTED(RESOURCE)
    ELSE
        CALL MPL_ALLOCATOR_INIT()
        CALL CHECK_MPL_RESOURCE_IS_EXPECTED()
    ENDIF
    CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.TRUE.)
    IF (MPL_ALLOCATOR_ALLOCATED() /= 0 ) CALL WARN("Expected: MPL_ALLOCATOR_ALLOCATED() == 0")
    IF (MPL_ALLOCATOR_CAPACITY() /= 0 .AND. MPL_ALLOCATOR_CAPACITY() /= -1) CALL WARN("Expected: MPL_ALLOCATOR_CAPACITY() == 0")
    CALL MPL_ALLOCATOR_RESERVE(SIZE=INT(1024*1024,JPIB))
    IF (MPL_ALLOCATOR_ALLOCATED() /= 0 ) CALL WARN("Expected: MPL_ALLOCATOR_ALLOCATED() == 0")
    IF (MPL_ALLOCATOR_CAPACITY() == 0 .AND. MPL_ALLOCATOR_CAPACITY() /= -1) CALL WARN("Expected: MPL_ALLOCATOR_CAPACITY() > 0")
    CALL VARIOUS_ALLOCATIONS_WITH_SHAPE
    CALL VARIOUS_ALLOCATIONS_WITH_BOUNDS
    IF (MPL_ALLOCATOR_ALLOCATED() /= 0 ) CALL WARN("Expected: MPL_ALLOCATOR_ALLOCATED() == 0")
    CALL MPL_ALLOCATOR_FINAL()
END SUBROUTINE TEST_INIT_AND_RESERVE

!----------------------------------------------------------------------------------------------------------------------------------

END MODULE

!----------------------------------------------------------------------------------------------------------------------------------
! This is the driver program that runs the tests in the above module
!----------------------------------------------------------------------------------------------------------------------------------

PROGRAM TEST_MPL_ALLOCATOR_DRIVER
USE TEST_MPL_ALLOCATOR
USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : OUTPUT_UNIT
USE MPL_MODULE, ONLY : MPL_INIT, MPL_END, MPL_OUTPUT, MPL_UNIT
IMPLICIT NONE

INTEGER                         :: ARGC, IARG
CHARACTER(LEN=512), ALLOCATABLE :: ARGV(:)
CHARACTER(LEN=512) :: TEST_NAME
ARGC = COMMAND_ARGUMENT_COUNT()
ALLOCATE(ARGV(ARGC))
DO IARG = 1, ARGC
    CALL GET_COMMAND_ARGUMENT(IARG, ARGV(IARG))
END DO

IF (MPL()) THEN
    CALL MPL_INIT(KOUTPUT=1)
ELSE
    MPL_UNIT=OUTPUT_UNIT
    MPL_OUTPUT=1
ENDIF

IF( ARGC > 0 ) THEN
    TEST_NAME = ARGV(1)
    IF (TEST_NAME /= "") THEN
        WRITE(OUTPUT_UNIT,'(A)') "Running test: "//TRIM(TEST_NAME)
        IF (TEST_NAME == "fiat_test_mpl_allocator_no_init") THEN
            CALL TEST_NO_INIT()
        ELSE IF (TEST_NAME == "fiat_test_mpl_allocator_init") THEN
            CALL TEST_INIT_NO_SIZE()
        ELSE IF (TEST_NAME == "fiat_test_mpl_allocator_init_FORTRAN") THEN
            CALL TEST_INIT_NO_SIZE(RESOURCE="FORTRAN")
        ELSE IF (TEST_NAME == "fiat_test_mpl_allocator_init_BUDDY_ALLOC") THEN
            CALL TEST_INIT_NO_SIZE(RESOURCE="BUDDY_ALLOC")
        ELSE IF (TEST_NAME == "fiat_test_mpl_allocator_init_MPI_POOL") THEN
            CALL TEST_INIT_NO_SIZE(RESOURCE="MPI_POOL")
        ELSE IF (TEST_NAME == "fiat_test_mpl_allocator_init_size") THEN
            CALL TEST_INIT_SIZE()
        ELSE IF (TEST_NAME == "fiat_test_mpl_allocator_init_size_FORTRAN") THEN
            CALL TEST_INIT_SIZE(RESOURCE="FORTRAN")
        ELSE IF (TEST_NAME == "fiat_test_mpl_allocator_init_size_BUDDY_ALLOC") THEN
            CALL TEST_INIT_SIZE(RESOURCE="BUDDY_ALLOC")
        ELSE IF (TEST_NAME == "fiat_test_mpl_allocator_init_size_MPI_POOL") THEN
            CALL TEST_INIT_SIZE(RESOURCE="MPI_POOL")
        ELSE IF (TEST_NAME == "fiat_test_mpl_allocator_init_and_reserve") THEN
            CALL TEST_INIT_AND_RESERVE()
        ELSE IF (TEST_NAME == "fiat_test_mpl_allocator_init_and_reserve_FORTRAN") THEN
            CALL TEST_INIT_AND_RESERVE(RESOURCE="FORTRAN")
        ELSE IF (TEST_NAME == "fiat_test_mpl_allocator_init_and_reserve_BUDDY_ALLOC") THEN
            CALL TEST_INIT_AND_RESERVE(RESOURCE="BUDDY_ALLOC")
        ELSE IF (TEST_NAME == "fiat_test_mpl_allocator_init_and_reserve_MPI_POOL") THEN
            CALL TEST_INIT_AND_RESERVE(RESOURCE="MPI_POOL")
        ELSE
            CALL FAIL("Unrecognized testname "//TRIM(TEST_NAME))
        ENDIF
    ENDIF
ELSE
    CALL FAIL("No test name provided as argument")
ENDIF

if (MPL()) CALL MPL_END(LDMEMINFO=.FALSE.)

CONTAINS

FUNCTION MPL() RESULT(LMPL)
    LOGICAL :: LMPL
    CHARACTER(LEN=512) :: ENV
    CALL GET_ENVIRONMENT_VARIABLE("MPL",ENV)
    IF( ENV == '0' ) THEN
        LMPL = .FALSE.
    ELSE
        LMPL = .TRUE.
    ENDIF
END FUNCTION

END PROGRAM TEST_MPL_ALLOCATOR_DRIVER
