! (C) Copyright 2026- ECMWF.
! (C) Copyright 2026- Meteo-France.
! 
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.

MODULE TEST_MPL_INIT_ALLOCATOR
USE EC_PARKIND, ONLY : JPIM
USE, INTRINSIC :: ISO_FORTRAN_ENV, ONLY : ERROR_UNIT
USE MPL_MODULE, ONLY : MPL_INIT, MPL_END
USE MPL_ALLOCATOR_MOD, ONLY : MPL_ALLOCATOR_CONFIG, MPL_ALLOCATOR_INITIALIZED, MPL_ALLOCATOR_RESOURCE, MPL_ALLOCATE, &
                            & MPL_DEALLOCATE
IMPLICIT NONE

CONTAINS

SUBROUTINE FAIL(MSG)
  CHARACTER(LEN=*), INTENT(IN) :: MSG
  WRITE(ERROR_UNIT,'(A)') TRIM(MSG)
  ERROR STOP 1
END SUBROUTINE FAIL

FUNCTION GET_EXPECTED_RESOURCE_FROM_ENV() RESULT(CMPL_RESOURCE)
  CHARACTER(LEN=512) :: CMPL_RESOURCE
  CALL GET_ENVIRONMENT_VARIABLE("EXPECTED_MPL_ALLOCATOR_RESOURCE", CMPL_RESOURCE)
END FUNCTION GET_EXPECTED_RESOURCE_FROM_ENV

SUBROUTINE CHECK_MPL_ALLOCATOR_IS_INITIALIZED(EXPECTED)
  LOGICAL, INTENT(IN) :: EXPECTED
  IF (MPL_ALLOCATOR_INITIALIZED() .NEQV. EXPECTED) THEN
    IF (EXPECTED) THEN
      CALL FAIL("Expected: MPL_ALLOCATOR_INITIALIZED() == .TRUE.")
    ELSE
      CALL FAIL("Expected: MPL_ALLOCATOR_INITIALIZED() == .FALSE.")
    END IF
  END IF
END SUBROUTINE CHECK_MPL_ALLOCATOR_IS_INITIALIZED

SUBROUTINE CHECK_MPL_ALLOCATOR_RESOURCE_IS_EXPECTED()
  CHARACTER(LEN=512) :: CLEXPECTED_RESOURCE
  CLEXPECTED_RESOURCE = GET_EXPECTED_RESOURCE_FROM_ENV()
  IF (LEN_TRIM(CLEXPECTED_RESOURCE) > 0) THEN
    IF (.NOT. MPL_ALLOCATOR_INITIALIZED()) THEN
      CALL FAIL("Expected MPL allocator to be initialized before checking resource")
    END IF
    IF (MPL_ALLOCATOR_RESOURCE() /= TRIM(CLEXPECTED_RESOURCE)) THEN
      CALL FAIL("Expected: MPL_ALLOCATOR_RESOURCE() == "//TRIM(CLEXPECTED_RESOURCE)//" whereas MPL_ALLOCATOR_RESOURCE() == "&
              &//TRIM(MPL_ALLOCATOR_RESOURCE()))
    END IF
  END IF
END SUBROUTINE CHECK_MPL_ALLOCATOR_RESOURCE_IS_EXPECTED

SUBROUTINE TEST_ENV_MANAGED_0()
  CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
  CALL MPL_INIT(KOUTPUT=0, LDINFO=.FALSE.)
  CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
  CALL MPL_END(LDMEMINFO=.FALSE.)
  CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
END SUBROUTINE TEST_ENV_MANAGED_0

SUBROUTINE TEST_ENV_MANAGED_1()
  CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
  CALL MPL_INIT(KOUTPUT=0, LDINFO=.FALSE.)
  CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.TRUE.)
  CALL CHECK_MPL_ALLOCATOR_RESOURCE_IS_EXPECTED()
  CALL MPL_END(LDMEMINFO=.FALSE.)
  CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
END SUBROUTINE TEST_ENV_MANAGED_1

SUBROUTINE TEST_CONFIG_MANAGED_0()
  MPL_ALLOCATOR_CONFIG%MPL_MANAGED = 0
  CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
  CALL MPL_INIT(KOUTPUT=0, LDINFO=.FALSE.)
  CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
  CALL MPL_END(LDMEMINFO=.FALSE.)
  CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
END SUBROUTINE TEST_CONFIG_MANAGED_0

SUBROUTINE TEST_CONFIG_MANAGED_1()
  MPL_ALLOCATOR_CONFIG%MPL_MANAGED = 1
  CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
  CALL MPL_INIT(KOUTPUT=0, LDINFO=.FALSE.)
  CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.TRUE.)
  CALL CHECK_MPL_ALLOCATOR_RESOURCE_IS_EXPECTED()
  CALL MPL_END(LDMEMINFO=.FALSE.)
  CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
END SUBROUTINE TEST_CONFIG_MANAGED_1

SUBROUTINE TEST_ENV_SIZE_FORBIDS_GROWTH()
  INTEGER(JPIM), POINTER :: ARRAY(:)
  CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
  CALL MPL_INIT(KOUTPUT=0, LDINFO=.FALSE.)
  CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.TRUE.)
  CALL CHECK_MPL_ALLOCATOR_RESOURCE_IS_EXPECTED()

  CALL MPL_ALLOCATE("ARRAY", ARRAY, SHAPE=[4096])
  CALL FAIL("Expected MPL_ALLOCATOR_SIZE to create a fixed-size pool during managed MPL_INIT")
END SUBROUTINE TEST_ENV_SIZE_FORBIDS_GROWTH

SUBROUTINE TEST_DEFAULT_ALLOW_GROWTH()
  INTEGER(JPIM), POINTER :: ARRAY(:)
  CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.FALSE.)
  CALL MPL_INIT(KOUTPUT=0, LDINFO=.FALSE.)
  CALL CHECK_MPL_ALLOCATOR_IS_INITIALIZED(.TRUE.)
  CALL CHECK_MPL_ALLOCATOR_RESOURCE_IS_EXPECTED()
  CALL MPL_ALLOCATE("ARRAY", ARRAY, SHAPE=[4096])
  CALL MPL_DEALLOCATE("ARRAY", ARRAY)
  CALL MPL_END(LDMEMINFO=.FALSE.)
END SUBROUTINE TEST_DEFAULT_ALLOW_GROWTH


END MODULE TEST_MPL_INIT_ALLOCATOR

PROGRAM TEST_MPL_INIT_ALLOCATOR_DRIVER
USE TEST_MPL_INIT_ALLOCATOR
IMPLICIT NONE

CHARACTER(LEN=512) :: TEST_NAME

CALL GET_COMMAND_ARGUMENT(1, TEST_NAME)
IF (LEN_TRIM(TEST_NAME) == 0) THEN
  CALL FAIL("No test name provided as argument")
END IF

IF (TEST_NAME == "fiat_test_mpl_init_allocator_env_managed0") THEN
  CALL TEST_ENV_MANAGED_0()
ELSE IF (TEST_NAME == "fiat_test_mpl_init_allocator_env_managed1") THEN
  CALL TEST_ENV_MANAGED_1()
ELSE IF (TEST_NAME == "fiat_test_mpl_init_allocator_config_managed0") THEN
  CALL TEST_CONFIG_MANAGED_0()
ELSE IF (TEST_NAME == "fiat_test_mpl_init_allocator_config_managed1") THEN
  CALL TEST_CONFIG_MANAGED_1()
ELSE IF (TEST_NAME == "fiat_test_mpl_init_allocator_env_size_forbids_grow") THEN
  CALL TEST_ENV_SIZE_FORBIDS_GROWTH()
ELSE IF (TEST_NAME == "fiat_test_mpl_init_allocator_default_allow_growth") THEN
  CALL TEST_DEFAULT_ALLOW_GROWTH()
ELSE
  CALL FAIL("Unrecognized test name: "//TRIM(TEST_NAME))
END IF

END PROGRAM TEST_MPL_INIT_ALLOCATOR_DRIVER