SUBROUTINE ABOR1(CDTEXT)

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK

USE YOMLUN   , ONLY : NULOUT   ,NULERR
USE YOMCT0   , ONLY : NPROC
USE YOMMP    , ONLY : MYPROC
USE MPL_MODULE, ONLY : MPL_ABORT
USE SDL_MODULE, ONLY : SDL_TRACEBACK, SDL_SRLABORT

IMPLICIT NONE

CHARACTER(LEN=*)                 :: CDTEXT ! UNDETERMINED INTENT
INTEGER(KIND=JPIM) :: ILEN
REAL(KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('ABOR1',0,ZHOOK_HANDLE)
ILEN=LEN(CDTEXT)
WRITE(NULOUT,'(1X,A)') 'ABOR1 CALLED'

IF(ILEN <= 512) THEN
  WRITE(NULOUT,'(1X,A)') CDTEXT
  WRITE(NULERR,'(1X,A,1X,I3,1X,A)') 'ABORT! ',MYPROC,CDTEXT
ELSE
  WRITE(NULERR,'(1X,A,1X,I3,1X,A)') 'ABORT! ',MYPROC,&
   & 'ABOR1 CALLED WITHOUT TEXT STRING'  
ENDIF
CLOSE(NULOUT)

IF (NPROC > 1) THEN
  IF(ILEN <= 512) THEN
    CALL MPL_ABORT(CDTEXT)
  ELSE
    CALL MPL_ABORT
  ENDIF
ELSE
  CALL SDL_TRACEBACK
  CALL FLUSH(0)
  CALL SDL_SRLABORT
ENDIF

IF (LHOOK) CALL DR_HOOK('ABOR1',1,ZHOOK_HANDLE)
END SUBROUTINE ABOR1
