SUBROUTINE CDRHOOKINIT()
!-- Makes sure Dr.Hook gets properly initialized from C-main program, too
USE PARKIND1  ,ONLY  : JPRB
USE YOMHOOK   ,ONLY  : LHOOK, DR_HOOK
IMPLICIT NONE
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('CDRHOOKINIT',0,ZHOOK_HANDLE)
IF (LHOOK) CALL DR_HOOK('CDRHOOKINIT',1,ZHOOK_HANDLE)
END SUBROUTINE CDRHOOKINIT
