SUBROUTINE DR_HOOK_PROCINFO(KMYPROC, KNPROC)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE MPL_MODULE, ONLY : MPL_RANK,MPL_NUMPROC
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(OUT) :: KMYPROC, KNPROC
KMYPROC = MPL_RANK
KNPROC = MPL_NUMPROC
END SUBROUTINE DR_HOOK_PROCINFO
