SUBROUTINE DR_HOOK_UTIL(CDNAME,KCASE,PKEY)
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK,ONLY : LHOOK
USE YOMOML,ONLY : OML_MAX_THREADS,OML_MY_THREAD
IMPLICIT NONE
CHARACTER(LEN=*),INTENT(IN) :: CDNAME
INTEGER(KIND=JPIM),INTENT(IN) :: KCASE
REAL(KIND=JPRB),INTENT(INOUT) :: PKEY


LOGICAL,SAVE :: LL_FIRST_TIME = .TRUE.
CHARACTER(LEN=256),SAVE :: CLENV
INTEGER(KIND=JPIM) INUMTIDS, IMYTID

! -----------------------------------------------------------------

IF (.NOT.LHOOK) RETURN
IF (LL_FIRST_TIME) THEN
  LL_FIRST_TIME = .FALSE.
  CALL GETENV('DR_HOOK',CLENV)
  IF (CLENV == ' ' .OR. CLENV == '0') THEN
    LHOOK = .FALSE.
    RETURN
  ENDIF
  CALL GETARG(0, CLENV)
  INUMTIDS = OML_MAX_THREADS()
  CALL C_DRHOOK_INIT(CLENV, INUMTIDS)
ENDIF
IMYTID = OML_MY_THREAD()
IF (KCASE == 0) THEN
  CALL C_DRHOOK_START(CDNAME, IMYTID, PKEY)
ELSE IF (KCASE == 1) THEN
  CALL C_DRHOOK_END(CDNAME, IMYTID, PKEY)
ENDIF

END SUBROUTINE DR_HOOK_UTIL
