SUBROUTINE DR_HOOK_PRT(KUNIT, CDSTR)
#include "tsmbkind.h"
IMPLICIT NONE
INTEGER_M, INTENT(IN) :: KUNIT
CHARACTER(LEN=*), INTENT(IN) :: CDSTR

IF (KUNIT < 0) THEN
  WRITE(*,'(A)') CDSTR
ELSE
  WRITE(KUNIT,'(A)') CDSTR
ENDIF

END SUBROUTINE DR_HOOK_PRT
