SUBROUTINE GSTATS_BARRIER2(KNUM)

USE PARKIND1  ,ONLY : JPIM     ,JPRB

USE YOMGSTATS, ONLY : LBARRIER_STATS2,NBAR_PTR,NBAR2
USE MPL_MODULE  , ONLY : MPL_BARRIER

IMPLICIT NONE

INTEGER(KIND=JPIM) :: KNUM
INTEGER(KIND=JPIM) :: INUM

IF(LBARRIER_STATS2)THEN
  IF(NBAR_PTR(KNUM) == 0) THEN
    INUM=NBAR2
    NBAR2=NBAR2+1
    NBAR_PTR(KNUM)=INUM
  ENDIF
  INUM=NBAR_PTR(KNUM)
  CALL GSTATS(INUM,0)
  CALL MPL_BARRIER()
  CALL GSTATS(INUM,1)
ENDIF

END SUBROUTINE GSTATS_BARRIER2

