SUBROUTINE GSTATS_LABEL(KNUM,CTYPE,CDESC)

USE PARKIND1  ,ONLY : JPIM     ,JPRB

USE YOMGSTATS

IMPLICIT NONE

INTEGER(KIND=JPIM) :: KNUM
CHARACTER(*) CDESC
CHARACTER(*) CTYPE
INTEGER(KIND=JPIM) :: ILEN, ITLEN

IF(KNUM < 0 .OR. KNUM>JPMAXSTAT) CALL ABOR1('GSTATS_LABEL:ILLEGAL KNUM')
ILEN = LEN(CDESC)
ILEN = MIN(ILEN,50)
ITLEN = LEN(CTYPE)
ITLEN = MIN(ILEN,3)
IF(CCDESC(KNUM) == '') THEN
  CCDESC(KNUM) = CDESC(1:ILEN)
  CCTYPE(KNUM) = CTYPE(1:ITLEN)
ELSEIF(CCDESC(KNUM)(1:ILEN) /= CDESC(1:ILEN)) THEN
  WRITE(JPERR,*)'LABEL',KNUM,' USED ',CCDESC(KNUM)
  CALL ABOR1('GSTATS_LABEL:OVERWRITE OF USED LABEL')
ENDIF

END SUBROUTINE GSTATS_LABEL

