SUBROUTINE GSTATS_LABEL(KNUM,CDESC)

#include "tsmbkind.h"

USE YOMGSTATS  
IMPLICIT NONE

INTEGER_M :: KNUM
CHARACTER(*) CDESC
INTEGER_M :: ILEN

IF(KNUM < 0 .OR. KNUM>JPMAXSTAT) CALL ABOR1('GSTATS_LABEL:ILLEGAL KNUM')
ILEN = LEN(CDESC)
ILEN = MIN(ILEN,50)
IF(CCDESC(KNUM) == '') THEN
  CCDESC(KNUM) = CDESC(1:ILEN)
ELSE
  WRITE(JPERR,*)'LABEL',KNUM,' USED ',CCDESC(KNUM)
  CALL ABOR1('GSTATS_LABEL:OVERWRITE OF USED LABEL')
ENDIF

END SUBROUTINE GSTATS_LABEL

