SUBROUTINE GSTATS_LABEL(KNUM,CDESC)

USE PARKIND1  ,ONLY : JPIM     ,JPRB

USE YOMGSTATS  
IMPLICIT NONE

INTEGER(KIND=JPIM) :: KNUM
CHARACTER(*) CDESC
INTEGER(KIND=JPIM) :: ILEN

IF(KNUM < 0 .OR. KNUM>JPMAXSTAT) CALL ABOR1('GSTATS_LABEL:ILLEGAL KNUM')
ILEN = LEN(CDESC)
ILEN = MIN(ILEN,50)
IF(CCDESC(KNUM) == '') THEN
  CCDESC(KNUM) = CDESC(1:ILEN)
ELSEIF(CCDESC(KNUM)(1:ILEN) /= CDESC(1:ILEN)) THEN
  WRITE(JPERR,*)'LABEL',KNUM,' USED ',CCDESC(KNUM)
  CALL ABOR1('GSTATS_LABEL:OVERWRITE OF USED LABEL')
ENDIF

END SUBROUTINE GSTATS_LABEL

